Eigen-unsupported: SkylineInplaceLU< MatrixType > Class Template Reference
SkylineInplaceLU< MatrixType > Class Template Reference
Detailed Description
template<typename MatrixType>
class Eigen::SkylineInplaceLU< MatrixType >
Inplace LU decomposition of a skyline matrix and associated features.
Parameters
MatrixType the type of the matrix of which we are computing the LU factorization
Public Member Functions
void compute ()
int flags () const
RealScalar precision () const
void setFlags (int f)
void setPrecision (RealScalar v)
SkylineInplaceLU (MatrixType &matrix, int flags=0)
template<typename BDerived , typename XDerived >
bool solve (const MatrixBase< BDerived > &b, MatrixBase< XDerived > *x, const int transposed=0) const
bool succeeded (void) const
Constructor & Destructor Documentation
SkylineInplaceLU()
SkylineInplaceLU (MatrixType & matrix, int flags = 0) inline
Creates a LU object and compute the respective factorization of matrix using flags flags.
References SkylineInplaceLU< MatrixType >::compute().
Member Function Documentation
compute()
void compute ()
Computes/re-computes the LU factorization
Computes / recomputes the in place LU decomposition of the SkylineInplaceLU. using the default algorithm.
Referenced by SkylineInplaceLU< MatrixType >::flags(), and SkylineInplaceLU< MatrixType >::SkylineInplaceLU().
flags()
int flags () const inline
Returns
the current flags
References SkylineInplaceLU< MatrixType >::compute(), and SkylineInplaceLU< MatrixType >::solve().
precision()
RealScalar precision () const inline
Returns
the current precision.
See also
setPrecision()
setFlags()
void setFlags (int f) inline
Sets the flags. Possible values are:
CompleteFactorization
IncompleteFactorization
MemoryEfficient
one of the ordering methods
etc...
See also
flags()
setPrecision()
void setPrecision (RealScalar v) inline
Sets the relative threshold value used to prune zero coefficients during the decomposition.
Setting a value greater than zero speeds up computation, and yields to an imcomplete factorization with fewer non zero coefficients. Such approximate factors are especially useful to initialize an iterative solver.
Note that the exact meaning of this parameter might depends on the actual backend. Moreover, not all backends support this feature.
See also
precision()
solve()
bool solve (const MatrixBase< BDerived > & b, MatrixBase< XDerived > * x, const int transposed = 0) const
Returns
the lower triangular matrix L
the upper triangular matrix U
Computes *x = U^-1 L^-1 b
If transpose is set to SvTranspose or SvAdjoint, the solution of the transposed/adjoint system is computed instead.
Not all backends implement the solution of the transposed or adjoint system.
Referenced by SkylineInplaceLU< MatrixType >::flags().
succeeded()
bool succeeded (void) const inline
Returns
true if the factorization succeeded
The documentation for this class was generated from the following file:
SkylineInplaceLU.h