Eigen-unsupported: SkylineMatrixBase< Derived > Class Template Reference
SkylineMatrixBase< Derived > Class Template Reference
Detailed Description
template<typename Derived>
class Eigen::SkylineMatrixBase< Derived >
Base class of any skyline matrices or skyline expressions.
Parameters
Derived
Inherits EigenBase< Derived >.
Public Types
enum {
RowsAtCompileTime,
ColsAtCompileTime,
SizeAtCompileTime ,
IsVectorAtCompileTime,
Flags,
CoeffReadCost
}
Public Member Functions
Index cols () const
const internal::eval< Derived, IsSkyline >::type eval () const
Index innerSize () const
Index nonZeros () const
Index outerSize () const
Index rows () const
Index size () const
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
CoeffReadCost
This is a rough measure of how expensive it is to read one coefficient from this expression.
Member Function Documentation
cols()
Index cols () const inline
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
Referenced by SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::innerSize(), SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::outerSize(), and SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::size().
eval()
const internal::eval<Derived, IsSkyline>::type eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
innerSize()
Index innerSize () const inline
Returns
the size of the inner dimension according to the storage order, i.e., the number of rows for a columns major matrix, and the number of cols otherwise
nonZeros()
Index nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
outerSize()
Index outerSize () const inline
Returns
the size of the storage major dimension, i.e., the number of columns for a columns major matrix, and the number of rows otherwise
rows()
Index rows () const inline
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
Referenced by SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::innerSize(), SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::outerSize(), and SkylineMatrixBase< SkylineMatrix< _Scalar, _Options > >::size().
size()
Index size () const inline
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
The documentation for this class was generated from the following files:
SkylineMatrixBase.h
SkylineProduct.h