Eigen-unsupported: SVDBase< _MatrixType > Class Template Reference
SVDBase< _MatrixType > Class Template Reference
Detailed Description
template<typename _MatrixType>
class Eigen::SVDBase< _MatrixType >
Mother class of SVD classes algorithms.
Parameters
MatrixType the type of the matrix of which we are computing the SVD decomposition SVD decomposition consists in decomposing any n-by-p matrix A as a product
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, but the computation is guaranteed to terminate in finite (and reasonable) time.
See also
MatrixBase::genericSvd()
Public Member Functions
SVDBase & compute (const MatrixType &matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
SVDBase & compute (const MatrixType &matrix)
Method performing the decomposition of given matrix using current options.
bool computeU () const
bool computeV () const
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
Index nonzeroSingularValues () const
const SingularValuesType & singularValues () const
Protected Member Functions
SVDBase ()
Default Constructor.
Constructor & Destructor Documentation
SVDBase()
SVDBase () inline protected
Default Constructor.
Default constructor of SVDBase
Member Function Documentation
compute() [1/2]
SVDBase& compute (const MatrixType & matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are #ComputeFullU, #ComputeThinU, #ComputeFullV, #ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
compute() [2/2]
SVDBase& compute (const MatrixType & matrix)
Method performing the decomposition of given matrix using current options.
Parameters
matrix the matrix to decompose
This method uses the current computationOptions, as already passed to the constructor or to compute(const MatrixType&, unsigned int).
computeU()
bool computeU () const inline
Returns
true if U (full or thin) is asked for in this SVD decomposition
Referenced by BDCSVD< _MatrixType >::compute(), SVDBase< _MatrixType >::matrixU(), and BDCSVD< _MatrixType >::solve().
computeV()
bool computeV () const inline
Returns
true if V (full or thin) is asked for in this SVD decomposition
Referenced by BDCSVD< _MatrixType >::compute(), SVDBase< _MatrixType >::matrixV(), and BDCSVD< _MatrixType >::solve().
matrixU()
const MatrixUType& matrixU () const inline
Returns
the U matrix.
For the SVDBase decomposition of a n-by-p matrix, letting m be the minimum of n and p, the U matrix is n-by-n if you asked for #ComputeFullU, and is n-by-m if you asked for #ComputeThinU.
The m first columns of U are the left singular vectors of the matrix being decomposed.
This method asserts that you asked for U to be computed.
References SVDBase< _MatrixType >::computeU().
Referenced by BDCSVD< _MatrixType >::compute().
matrixV()
const MatrixVType& matrixV () const inline
Returns
the V matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the V matrix is p-by-p if you asked for #ComputeFullV, and is p-by-m if you asked for ComputeThinV.
The m first columns of V are the right singular vectors of the matrix being decomposed.
This method asserts that you asked for V to be computed.
References SVDBase< _MatrixType >::computeV().
Referenced by BDCSVD< _MatrixType >::compute().
nonzeroSingularValues()
Index nonzeroSingularValues () const inline
Returns
the number of singular values that are not exactly 0
singularValues()
const SingularValuesType& singularValues () const inline
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
Referenced by BDCSVD< _MatrixType >::compute().
The documentation for this class was generated from the following file:
SVDBase.h