Eigen-unsupported: BDCSVD< _MatrixType > Class Template Reference
BDCSVD< _MatrixType > Class Template Reference
Detailed Description
template<typename _MatrixType>
class Eigen::BDCSVD< _MatrixType >
class Bidiagonal Divide and Conquer SVD
Parameters
MatrixType the type of the matrix of which we are computing the SVD decomposition We plan to have a very similar interface to JacobiSVD on this class. It should be used to speed up the calcul of SVD for big matrices.
Public Member Functions
BDCSVD ()
Default Constructor.
BDCSVD (Index rows, Index cols, unsigned int computationOptions=0)
Default Constructor with memory preallocation.
BDCSVD (const MatrixType &matrix, unsigned int computationOptions=0)
Constructor performing the decomposition of given matrix.
SVDBase< MatrixType > & compute (const MatrixType &matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
SVDBase< MatrixType > & compute (const MatrixType &matrix)
Method performing the decomposition of given matrix using current options.
bool computeU () const
bool computeV () const
Index nonzeroSingularValues () const
const SingularValuesType & singularValues () const
template<typename Rhs >
const internal::solve_retval< BDCSVD, Rhs > solve (const MatrixBase< Rhs > &b) const
Constructor & Destructor Documentation
BDCSVD() [1/3]
BDCSVD () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via BDCSVD::compute(const MatrixType&).
BDCSVD() [2/3]
BDCSVD (Index rows, Index cols, unsigned int computationOptions = 0) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
BDCSVD()
BDCSVD() [3/3]
BDCSVD (const MatrixType & matrix, unsigned int computationOptions = 0) inline
Constructor performing the decomposition of given matrix.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit - field, the possible bits are #ComputeFullU, #ComputeThinU, #ComputeFullV, #ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non - default) FullPivHouseholderQR preconditioner.
References BDCSVD< _MatrixType >::compute().
Member Function Documentation
compute() [1/2]
SVDBase< MatrixType > & compute (const MatrixType & matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit - field, the possible bits are #ComputeFullU, #ComputeThinU, #ComputeFullV, #ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non - default) FullPivHouseholderQR preconditioner.
References SVDBase< _MatrixType >::computeU(), SVDBase< _MatrixType >::computeV(), SVDBase< _MatrixType >::matrixU(), SVDBase< _MatrixType >::matrixV(), and SVDBase< _MatrixType >::singularValues().
Referenced by BDCSVD< _MatrixType >::BDCSVD(), BDCSVD< _MatrixType >::compute(), and BDCSVD< _MatrixType >::solve().
compute() [2/2]
SVDBase<MatrixType>& compute (const MatrixType & matrix) inline
Method performing the decomposition of given matrix using current options.
Parameters
matrix the matrix to decompose
This method uses the current computationOptions, as already passed to the constructor or to compute(const MatrixType&, unsigned int).
References BDCSVD< _MatrixType >::compute().
computeU()
bool computeU () const inline inherited
Returns
true if U (full or thin) is asked for in this SVD decomposition
Referenced by BDCSVD< _MatrixType >::compute(), SVDBase< _MatrixType >::matrixU(), and BDCSVD< _MatrixType >::solve().
computeV()
bool computeV () const inline inherited
Returns
true if V (full or thin) is asked for in this SVD decomposition
Referenced by BDCSVD< _MatrixType >::compute(), SVDBase< _MatrixType >::matrixV(), and BDCSVD< _MatrixType >::solve().
nonzeroSingularValues()
Index nonzeroSingularValues () const inline inherited
Returns
the number of singular values that are not exactly 0
singularValues()
const SingularValuesType& singularValues () const inline inherited
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
Referenced by BDCSVD< _MatrixType >::compute().
solve()
const internal::solve_retval<BDCSVD, Rhs> solve (const MatrixBase< Rhs > & b) const inline
Returns
a (least squares) solution of using the current SVD decomposition of A.
Parameters
b the right - hand - side of the equation to solve.
Note
Solving requires both U and V to be computed. Thin U and V are enough, there is no need for full U or V.
SVD solving is implicitly least - squares. Thus, this method serves both purposes of exact solving and least - squares solving. In other words, the returned solution is guaranteed to minimize the Euclidean norm .
References BDCSVD< _MatrixType >::compute(), SVDBase< _MatrixType >::computeU(), and SVDBase< _MatrixType >::computeV().
The documentation for this class was generated from the following file:
BDCSVD.h