Eigen-unsupported: Eigen Namespace Reference
Eigen Namespace Reference
iterative scaling algorithm to equilibrate rows and column norms in matrices
Classes
class AutoDiffScalar
A scalar type replacement with automatic differentation capability.
class BDCSVD
class Bidiagonal Divide and Conquer SVD
class DGMRES
A Restarted GMRES with deflation. This class implements a modification of the GMRES solver for sparse linear systems. The basis is built with modified Gram-Schmidt. At each restart, a few approximated eigenvectors corresponding to the smallest eigenvalues are used to build a preconditioner for the next cycle. This preconditioner for deflation can be combined with any other preconditioner, the IncompleteLUT for instance. The preconditioner is applied at right of the matrix and the combination is multiplicative.
class DynamicSparseMatrix
A sparse matrix class designed for matrix assembly purpose.
class GMRES
A GMRES solver for sparse square problems.
class HybridNonLinearSolver
Finds a zero of a system of n nonlinear functions in n variables by a modification of the Powell hybrid method ("dogleg").
class IncompleteCholesky
Modified Incomplete Cholesky with dual threshold.
class IterationController
Controls the iterations of the iterative solvers.
class JacobiSVD
Two-sided Jacobi SVD decomposition of a rectangular matrix.
class KdBVH
A simple bounding volume hierarchy based on AlignedBox.
class KroneckerProduct
Kronecker tensor product helper class for dense matrices.
class KroneckerProductSparse
Kronecker tensor product helper class for sparse matrices.
class LevenbergMarquardt
Performs non linear optimization over a non-linear function, using a variant of the Levenberg Marquardt algorithm.
class MatrixExponential
Class for computing the matrix exponential.
struct MatrixExponentialReturnValue
Proxy for the matrix exponential of some matrix (expression).
class MatrixFunction
Class for computing matrix functions.
class MatrixFunctionAtomic
Helper class for computing matrix functions of atomic matrices.
class MatrixFunctionReturnValue
Proxy for the matrix function of some matrix (expression).
class MatrixLogarithmAtomic
Helper class for computing matrix logarithm of atomic matrices.
class MatrixLogarithmReturnValue
Proxy for the matrix logarithm of some matrix (expression).
class MatrixMarketIterator
Iterator to browse matrices from a specified folder.
class MatrixPower
Class for computing matrix powers.
class MatrixPowerReturnValue
Proxy for the matrix power of some matrix (expression).
class MatrixSquareRoot
Class for computing matrix square roots of general matrices.
class MatrixSquareRootQuasiTriangular
Class for computing matrix square roots of upper quasi-triangular matrices.
class MatrixSquareRootReturnValue
Proxy for the matrix square root of some matrix (expression).
class MatrixSquareRootTriangular
Class for computing matrix square roots of upper triangular matrices.
class MINRES
A minimal residual solver for sparse symmetric problems.
class NumericalDiff
class PolynomialSolver
A polynomial solver.
class PolynomialSolverBase
Defined to be inherited by polynomial solvers: it provides convenient methods such as.
class RandomSetter
The RandomSetter is a wrapper object allowing to set/update a sparse matrix with random access.
class SkylineInplaceLU
Inplace LU decomposition of a skyline matrix and associated features.
class SkylineMatrix
The main skyline matrix class.
class SkylineMatrixBase
Base class of any skyline matrices or skyline expressions.
class SkylineStorage
class Spline
A class representing multi-dimensional spline curves.
struct SplineFitting
Spline fitting methods.
struct SplineTraits< Spline< _Scalar, _Dim, _Degree >, _DerivativeOrder >
Compile-time attributes of the Spline class for fixed degree.
struct SplineTraits< Spline< _Scalar, _Dim, _Degree >, Dynamic >
Compile-time attributes of the Spline class for Dynamic degree.
struct StdMapTraits
class StdStemFunctions
Stem functions corresponding to standard mathematical functions.
class SVDBase
Mother class of SVD classes algorithms.
Typedefs
typedef Spline< double, 2 > Spline2d
2D double B-spline with dynamic degree.
typedef Spline< float, 2 > Spline2f
2D float B-spline with dynamic degree.
typedef Spline< double, 3 > Spline3d
3D double B-spline with dynamic degree.
typedef Spline< float, 3 > Spline3f
3D float B-spline with dynamic degree.
Functions
template<typename BVH , typename Intersector >
void BVIntersect (const BVH &tree, Intersector &intersector)
template<typename BVH1 , typename BVH2 , typename Intersector >
void BVIntersect (const BVH1 &tree1, const BVH2 &tree2, Intersector &intersector)
template<typename BVH , typename Minimizer >
Minimizer::Scalar BVMinimize (const BVH &tree, Minimizer &minimizer)
template<typename BVH1 , typename BVH2 , typename Minimizer >
Minimizer::Scalar BVMinimize (const BVH1 &tree1, const BVH2 &tree2, Minimizer &minimizer)
template<typename Polynomial >
NumTraits< typename Polynomial::Scalar >::Real cauchy_max_bound (const Polynomial &poly)
template<typename Polynomial >
NumTraits< typename Polynomial::Scalar >::Real cauchy_min_bound (const Polynomial &poly)
template<typename PointArrayType , typename KnotVectorType >
void ChordLengths (const PointArrayType &pts, KnotVectorType &chord_lengths)
Computes chord length parameters which are required for spline interpolation.
template<typename KnotVectorType >
void KnotAveraging (const KnotVectorType &parameters, DenseIndex degree, KnotVectorType &knots)
Computes knot averages.The knots are computed as
where is the degree and the number knots of the desired interpolating spline.
template<typename A , typename B >
KroneckerProduct< A, B > kroneckerProduct (const MatrixBase< A > &a, const MatrixBase< B > &b)
template<typename A , typename B >
KroneckerProductSparse< A, B > kroneckerProduct (const EigenBase< A > &a, const EigenBase< B > &b)
template<typename Polynomials , typename T >
T poly_eval (const Polynomials &poly, const T &x)
template<typename Polynomials , typename T >
T poly_eval_horner (const Polynomials &poly, const T &x)
template<typename RootVector , typename Polynomial >
void roots_to_monicPolynomial (const RootVector &rv, Polynomial &poly)
Detailed Description
iterative scaling algorithm to equilibrate rows and column norms in matrices
This class can be used as a preprocessing tool to accelerate the convergence of iterative methods
This feature is useful to limit the pivoting amount during LU/ILU factorization The scaling strategy as presented here preserves the symmetry of the problem NOTE It is assumed that the matrix does not have empty row or column,
Example with key steps
VectorXd x(n), b(n);
SparseMatrix<double> A;
// fill A and b;
IterScaling<SparseMatrix<double> > scal;
// Compute the left and right scaling vectors. The matrix is equilibrated at output
scal.computeRef(A);
// Scale the right hand side
b = scal.LeftScaling().cwiseProduct(b);
// Now, solve the equilibrated linear system with any available solver
// Scale back the computed solution
x = scal.RightScaling().cwiseProduct(x);
Template Parameters
_MatrixType the type of the matrix. It should be a real square sparsematrix
References : D. Ruiz and B. Ucar, A Symmetry Preserving Algorithm for Matrix Scaling, INRIA Research report RR-7552
See also
IncompleteLUT
Function Documentation
BVIntersect() [1/2]
void Eigen::BVIntersect (const BVH & tree, Intersector & intersector)
Given a BVH, runs the query encapsulated by intersector. The Intersector type must provide the following members:
bool intersectVolume(const BVH::Volume &volume) //returns true if volume intersects the query
bool intersectObject(const BVH::Object &object) //returns true if the search should terminate immediately
BVIntersect() [2/2]
void Eigen::BVIntersect (const BVH1 & tree1, const BVH2 & tree2, Intersector & intersector)
Given two BVH's, runs the query on their Cartesian product encapsulated by intersector. The Intersector type must provide the following members:
bool intersectVolumeVolume(const BVH1::Volume &v1, const BVH2::Volume &v2) //returns true if product of volumes intersects the query
bool intersectVolumeObject(const BVH1::Volume &v1, const BVH2::Object &o2) //returns true if the volume-object product intersects the query
bool intersectObjectVolume(const BVH1::Object &o1, const BVH2::Volume &v2) //returns true if the volume-object product intersects the query
bool intersectObjectObject(const BVH1::Object &o1, const BVH2::Object &o2) //returns true if the search should terminate immediately
BVMinimize() [1/2]
Minimizer::Scalar Eigen::BVMinimize (const BVH & tree, Minimizer & minimizer)
Given a BVH, runs the query encapsulated by minimizer.
Returns
the minimum value. The Minimizer type must provide the following members:
typedef Scalar //the numeric type of what is being minimized--not necessarily the Scalar type of the BVH (if it has one)
Scalar minimumOnVolume(const BVH::Volume &volume)
Scalar minimumOnObject(const BVH::Object &object)
BVMinimize() [2/2]
Minimizer::Scalar Eigen::BVMinimize (const BVH1 & tree1, const BVH2 & tree2, Minimizer & minimizer)
Given two BVH's, runs the query on their cartesian product encapsulated by minimizer.
Returns
the minimum value. The Minimizer type must provide the following members:
typedef Scalar //the numeric type of what is being minimized--not necessarily the Scalar type of the BVH (if it has one)
Scalar minimumOnVolumeVolume(const BVH1::Volume &v1, const BVH2::Volume &v2)
Scalar minimumOnVolumeObject(const BVH1::Volume &v1, const BVH2::Object &o2)
Scalar minimumOnObjectVolume(const BVH1::Object &o1, const BVH2::Volume &v2)
Scalar minimumOnObjectObject(const BVH1::Object &o1, const BVH2::Object &o2)
cauchy_max_bound()
NumTraits<typename Polynomial::Scalar>::Real Eigen::cauchy_max_bound (const Polynomial & poly) inline
Returns
a maximum bound for the absolute value of any root of the polynomial.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. is stored as a vector .
Precondition: the leading coefficient of the input polynomial poly must be non zero
cauchy_min_bound()
NumTraits<typename Polynomial::Scalar>::Real Eigen::cauchy_min_bound (const Polynomial & poly) inline
Returns
a minimum bound for the absolute value of any non zero root of the polynomial.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. is stored as a vector .
ChordLengths()
void Eigen::ChordLengths (const PointArrayType & pts, KnotVectorType & chord_lengths)
Computes chord length parameters which are required for spline interpolation.
Parameters
[in] pts The data points to which a spline should be fit.
[out] chord_lengths The resulting chord lenggth vector.
See also
Les Piegl and Wayne Tiller, The NURBS book (2nd ed.), 1997, 9.2.1 Global Curve Interpolation to Point Data
Referenced by SplineFitting< SplineType >::Interpolate().
KnotAveraging()
void Eigen::KnotAveraging (const KnotVectorType & parameters, DenseIndex degree, KnotVectorType & knots)
Computes knot averages.The knots are computed as
where is the degree and the number knots of the desired interpolating spline.
Parameters
[in] parameters The input parameters. During interpolation one for each data point.
[in] degree The spline degree which is used during the interpolation.
[out] knots The output knot vector.
See also
Les Piegl and Wayne Tiller, The NURBS book (2nd ed.), 1997, 9.2.1 Global Curve Interpolation to Point Data
Referenced by SplineFitting< SplineType >::Interpolate().
kroneckerProduct() [1/2]
KroneckerProduct<A,B> Eigen::kroneckerProduct (const MatrixBase< A > & a, const MatrixBase< B > & b)
Computes Kronecker tensor product of two dense matrices
Warning
If you want to replace a matrix by its Kronecker product with some matrix, do NOT do this:
A = kroneckerProduct(A,B); // bug!!! caused by aliasing effect
instead, use eval() to work around this:
A = kroneckerProduct(A,B).eval();
Parameters
a Dense matrix a
b Dense matrix b
Returns
Kronecker tensor product of a and b
kroneckerProduct() [2/2]
KroneckerProductSparse<A,B> Eigen::kroneckerProduct (const EigenBase< A > & a, const EigenBase< B > & b)
Computes Kronecker tensor product of two matrices, at least one of which is sparse
Parameters
a Dense/sparse matrix a
b Dense/sparse matrix b
Returns
Kronecker tensor product of a and b, stored in a sparse matrix
poly_eval()
T Eigen::poly_eval (const Polynomials & poly, const T & x) inline
Returns
the evaluation of the polynomial at x using stabilized Horner algorithm.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. is stored as a vector .
[in] x : the value to evaluate the polynomial at.
References poly_eval_horner().
poly_eval_horner()
T Eigen::poly_eval_horner (const Polynomials & poly, const T & x) inline
Returns
the evaluation of the polynomial at x using Horner algorithm.
Parameters
[in] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. is stored as a vector .
[in] x : the value to evaluate the polynomial at.
Note for stability:
Referenced by poly_eval().
roots_to_monicPolynomial()
void Eigen::roots_to_monicPolynomial (const RootVector & rv, Polynomial & poly)
Given the roots of a polynomial compute the coefficients in the monomial basis of the monic polynomial with same roots and minimal degree. If RootVector is a vector of complexes, Polynomial should also be a vector of complexes.
Parameters
[in] rv : a vector containing the roots of a polynomial.
[out] poly : the vector of coefficients of the polynomial ordered by degrees i.e. poly[i] is the coefficient of degree i of the polynomial e.g. is stored as a vector .