Eigen: SimplicialLDLT< _MatrixType, _UpLo, _Ordering > Class Template Reference
SimplicialLDLT< _MatrixType, _UpLo, _Ordering > Class Template Reference
Sparse linear algebra » Reference » SparseCholesky_Module
Detailed Description
template<typename _MatrixType, int _UpLo, typename _Ordering>
class Eigen::SimplicialLDLT< _MatrixType, _UpLo, _Ordering >
A direct sparse LDLT Cholesky factorizations without square root.
This class provides a LDL^T Cholesky factorizations without square root of sparse matrices that are selfadjoint and positive definite. The factorization allows for solving A.X = B where X and B can be either dense or sparse.
In order to reduce the fill-in, a symmetric permutation P is applied prior to the factorization such that the factorized matrix is P A P^-1.
Template Parameters
_MatrixType the type of the sparse matrix A, it must be a SparseMatrix<>
_UpLo the triangular part that will be used for the computations. It can be Lower or Upper. Default is Lower.
_Ordering The ordering method to use, either AMDOrdering<> or NaturalOrdering<>. Default is AMDOrdering<>
See also
class SimplicialLLT, class AMDOrdering, class NaturalOrdering
Public Member Functions
void analyzePattern (const MatrixType &a)
SimplicialLDLT & compute (const MatrixType &matrix)
Scalar determinant () const
void factorize (const MatrixType &a)
ComputationInfo info () const
Reports whether previous computation was successful.
const MatrixL matrixL () const
const MatrixU matrixU () const
const PermutationMatrix< Dynamic, Dynamic, Index > & permutationP () const
const PermutationMatrix< Dynamic, Dynamic, Index > & permutationPinv () const
SimplicialLDLT< _MatrixType, _UpLo, _Ordering > & setShift (const RealScalar &offset, const RealScalar &scale=1)
SimplicialLDLT ()
SimplicialLDLT (const MatrixType &matrix)
const internal::solve_retval< SimplicialCholeskyBase, Rhs > solve (const MatrixBase< Rhs > &b) const
const internal::sparse_solve_retval< SimplicialCholeskyBase, Rhs > solve (const SparseMatrixBase< Rhs > &b) const
const VectorType vectorD () const
Constructor & Destructor Documentation
SimplicialLDLT() [1/2]
SimplicialLDLT () inline
Default constructor
SimplicialLDLT() [2/2]
SimplicialLDLT (const MatrixType & matrix) inline
Constructs and performs the LLT factorization of matrix
Member Function Documentation
analyzePattern()
void analyzePattern (const MatrixType & a) inline
Performs a symbolic decomposition on the sparcity of matrix.
This function is particularly useful when solving for several problems having the same structure.
See also
factorize()
compute()
SimplicialLDLT& compute (const MatrixType & matrix) inline
Computes the sparse Cholesky decomposition of matrix
determinant()
Scalar determinant () const inline
Returns
the determinant of the underlying matrix from the current factorization
References SimplicialCholeskyBase< Derived >::compute().
factorize()
void factorize (const MatrixType & a) inline
Performs a numeric decomposition of matrix
The given matrix must has the same sparcity than the matrix on which the symbolic decomposition has been performed.
See also
analyzePattern()
info()
ComputationInfo info () const inline inherited
Reports whether previous computation was successful.
Returns
Success if computation was succesful, NumericalIssue if the matrix.appears to be negative.
matrixL()
const MatrixL matrixL () const inline
Returns
an expression of the factor L
matrixU()
const MatrixU matrixU () const inline
Returns
an expression of the factor U (= L^*)
permutationP()
const PermutationMatrix<Dynamic,Dynamic,Index>& permutationP () const inline inherited
Returns
the permutation P
See also
permutationPinv()
permutationPinv()
const PermutationMatrix<Dynamic,Dynamic,Index>& permutationPinv () const inline inherited
Returns
the inverse P^-1 of the permutation P
See also
permutationP()
setShift()
SimplicialLDLT< _MatrixType, _UpLo, _Ordering > & setShift (const RealScalar & offset, const RealScalar & scale = 1) inline inherited
Sets the shift parameters that will be used to adjust the diagonal coefficients during the numerical factorization.
During the numerical factorization, the diagonal coefficients are transformed by the following linear model:
d_ii = offset + scale * d_ii
The default is the identity transformation with offset=0, and scale=1.
Returns
a reference to *this.
References SparseMatrix< _Scalar, _Options, _Index >::cols(), SparseMatrix< _Scalar, _Options, _Index >::nonZeros(), SparseMatrix< _Scalar, _Options, _Index >::rows(), PermutationBase< Derived >::size(), and Eigen::Success.
solve() [1/2]
const internal::solve_retval<SimplicialCholeskyBase, Rhs> solve (const MatrixBase< Rhs > & b) const inline inherited
Returns
the solution x of using the current decomposition of A.
See also
compute()
solve() [2/2]
const internal::sparse_solve_retval<SimplicialCholeskyBase, Rhs> solve (const SparseMatrixBase< Rhs > & b) const inline inherited
Returns
the solution x of using the current decomposition of A.
See also
compute()
References EigenBase< Derived >::derived(), and SparseMatrixBase< Derived >::rows().
vectorD()
const VectorType vectorD () const inline
Returns
a vector expression of the diagonal D
The documentation for this class was generated from the following file:
SimplicialCholesky.h