Eigen: DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Detailed Description
template<typename _Scalar, int SizeAtCompileTime, int MaxSizeAtCompileTime>
class Eigen::DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >
Represents a diagonal matrix with its storage.
Parameters
_Scalar the type of coefficients
SizeAtCompileTime the dimension of the matrix, or Dynamic
MaxSizeAtCompileTime the dimension of the matrix, or Dynamic. This parameter is optional and defaults to SizeAtCompileTime. Most of the time, you do not need to specify it.
See also
class DiagonalWrapper
Inherits DiagonalBase< Derived >.
Public Member Functions
const DiagonalVectorType & diagonal () const
DiagonalVectorType & diagonal ()
DiagonalMatrix ()
DiagonalMatrix (Index dim)
DiagonalMatrix (const Scalar &x, const Scalar &y)
DiagonalMatrix (const Scalar &x, const Scalar &y, const Scalar &z)
template<typename OtherDerived >
DiagonalMatrix (const DiagonalBase< OtherDerived > &other)
template<typename OtherDerived >
DiagonalMatrix (const MatrixBase< OtherDerived > &other)
template<typename OtherDerived >
DiagonalMatrix & operator= (const DiagonalBase< OtherDerived > &other)
void resize (Index size)
void setIdentity ()
void setIdentity (Index size)
void setZero ()
void setZero (Index size)
Constructor & Destructor Documentation
DiagonalMatrix() [1/6]
DiagonalMatrix () inline
Default constructor without initialization
DiagonalMatrix() [2/6]
DiagonalMatrix (Index dim) inline
Constructs a diagonal matrix with given dimension
DiagonalMatrix() [3/6]
DiagonalMatrix (const Scalar & x, const Scalar & y) inline
2D constructor.
DiagonalMatrix() [4/6]
DiagonalMatrix (const Scalar & x, const Scalar & y, const Scalar & z) inline
3D constructor.
DiagonalMatrix() [5/6]
DiagonalMatrix (const DiagonalBase< OtherDerived > & other) inline
Copy constructor.
References DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal().
DiagonalMatrix() [6/6]
DiagonalMatrix (const MatrixBase< OtherDerived > & other) inline explicit
generic constructor from expression of the diagonal coefficients
Member Function Documentation
diagonal() [1/2]
const DiagonalVectorType& diagonal () const inline
const version of diagonal().
Referenced by DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::DiagonalMatrix(), and DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::operator=().
diagonal() [2/2]
DiagonalVectorType& diagonal () inline
Returns
a reference to the stored vector of diagonal coefficients.
operator=()
DiagonalMatrix& operator= (const DiagonalBase< OtherDerived > & other) inline
Copy operator.
References DiagonalMatrix< _Scalar, SizeAtCompileTime, MaxSizeAtCompileTime >::diagonal().
resize()
void resize (Index size) inline
Resizes to given size.
setIdentity() [1/2]
void setIdentity () inline
Sets this matrix to be the identity matrix of the current size.
setIdentity() [2/2]
void setIdentity (Index size) inline
Sets this matrix to be the identity matrix of the given size.
References Eigen::LvalueBit.
setZero() [1/2]
void setZero () inline
Sets all coefficients to zero.
setZero() [2/2]
void setZero (Index size) inline
Resizes and sets all coefficients to zero.
The documentation for this class was generated from the following file:
DiagonalMatrix.h