Eigen: ParametrizedLine< _Scalar, _AmbientDim, _Options > Class Template Reference
ParametrizedLine< _Scalar, _AmbientDim, _Options > Class Template Reference
Geometry » Reference » Geometry_Module
Detailed Description
template<typename _Scalar, int _AmbientDim, int _Options>
class Eigen::ParametrizedLine< _Scalar, _AmbientDim, _Options >
A parametrized line.
This is defined in the Geometry module.
#include <Eigen/Geometry>
A parametrized line is defined by an origin point and a unit direction vector such that the line corresponds to the set , .
Parameters
_Scalar the scalar type, i.e., the type of the coefficients
_AmbientDim the dimension of the ambient space, can be a compile time value or Dynamic.
Public Member Functions
template<typename NewScalarType >
internal::cast_return_type< ParametrizedLine, ParametrizedLine< NewScalarType, AmbientDimAtCompileTime, Options > >::type cast () const
Index dim () const
RealScalar distance (const VectorType &p) const
template<int OtherOptions>
_Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
_Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
template<int OtherOptions>
VectorType intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane) const
bool isApprox (const ParametrizedLine &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
ParametrizedLine ()
ParametrizedLine (Index _dim)
ParametrizedLine (const VectorType &origin, const VectorType &direction)
template<int OtherOptions>
ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > &hyperplane)
template<typename OtherScalarType , int OtherOptions>
ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > &other)
VectorType pointAt (const Scalar &t) const
VectorType projection (const VectorType &p) const
RealScalar squaredDistance (const VectorType &p) const
Static Public Member Functions
static ParametrizedLine Through (const VectorType &p0, const VectorType &p1)
Constructor & Destructor Documentation
ParametrizedLine() [1/5]
ParametrizedLine () inline
Default constructor without initialization
Referenced by ParametrizedLine< _Scalar, _AmbientDim, _Options >::cast(), ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection(), and ParametrizedLine< _Scalar, _AmbientDim, _Options >::Through().
ParametrizedLine() [2/5]
ParametrizedLine (Index _dim) inline explicit
Constructs a dynamic-size line with _dim the dimension of the ambient space
ParametrizedLine() [3/5]
ParametrizedLine (const VectorType & origin, const VectorType & direction) inline
Initializes a parametrized line of direction direction and origin origin.
Warning
the vector direction is assumed to be normalized.
References ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
ParametrizedLine() [4/5]
ParametrizedLine (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) inline explicit
Constructs a parametrized line from a 2D hyperplane
Warning
the ambient space must have dimension 2 such that the hyperplane actually describes a line
References Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), and Hyperplane< _Scalar, _AmbientDim, _Options >::offset().
ParametrizedLine() [5/5]
ParametrizedLine (const ParametrizedLine< OtherScalarType, AmbientDimAtCompileTime, OtherOptions > & other) inline explicit
Copy constructor with scalar type conversion
Member Function Documentation
cast()
internal::cast_return_type<ParametrizedLine, ParametrizedLine<NewScalarType,AmbientDimAtCompileTime,Options> >::type cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
References ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
dim()
Index dim () const inline
Returns
the dimension in which the line holds
distance()
RealScalar distance (const VectorType & p) const inline
Returns
the distance of a point p to its projection onto the line *this.
See also
squaredDistance()
References ParametrizedLine< _Scalar, _AmbientDim, _Options >::squaredDistance().
intersection()
_Scalar intersection (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Deprecated:
use intersectionParameter()
Returns
the parameter value of the intersection between *this and the given hyperplane
intersectionParameter()
_Scalar intersectionParameter (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the parameter value of the intersection between *this and the given hyperplane
References Hyperplane< _Scalar, _AmbientDim, _Options >::normal(), and Hyperplane< _Scalar, _AmbientDim, _Options >::offset().
intersectionPoint()
ParametrizedLine< _Scalar, _AmbientDim, _Options >::VectorType intersectionPoint (const Hyperplane< _Scalar, _AmbientDim, OtherOptions > & hyperplane) const inline
Returns
the point of the intersection between *this and the given hyperplane
References ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt().
Referenced by ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection().
isApprox()
bool isApprox (const ParametrizedLine< _Scalar, _AmbientDim, _Options > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
pointAt()
ParametrizedLine< _Scalar, _AmbientDim, _Options >::VectorType pointAt (const Scalar & t) const inline
Returns
the point at t along this line
Referenced by ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionPoint(), and ParametrizedLine< _Scalar, _AmbientDim, _Options >::projection().
projection()
VectorType projection (const VectorType & p) const inline
Returns
the projection of a point p onto the line *this.
References ParametrizedLine< _Scalar, _AmbientDim, _Options >::intersectionPoint(), ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine(), and ParametrizedLine< _Scalar, _AmbientDim, _Options >::pointAt().
squaredDistance()
RealScalar squaredDistance (const VectorType & p) const inline
Returns
the squared distance of a point p to its projection onto the line *this.
See also
distance()
Referenced by ParametrizedLine< _Scalar, _AmbientDim, _Options >::distance().
Through()
static ParametrizedLine Through (const VectorType & p0, const VectorType & p1) inline static
Constructs a parametrized line going from p0 to p1.
References ParametrizedLine< _Scalar, _AmbientDim, _Options >::ParametrizedLine().
The documentation for this class was generated from the following files:
ForwardDeclarations.h
ParametrizedLine.h