Eigen: DenseCoeffsBase< Derived, WriteAccessors > Class Template Reference
DenseCoeffsBase< Derived, WriteAccessors > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Detailed Description
template<typename Derived>
class Eigen::DenseCoeffsBase< Derived, WriteAccessors >
Base class providing read/write coefficient access to matrices and arrays.
Template Parameters
Derived Type of the derived class
#WriteAccessors Constant indicating read/write access
This class defines the non-const operator() function and friends, which can be used to write specific entries of a matrix or array. This class inherits DenseCoeffsBase<Derived, ReadOnlyAccessors> which defines the const variant for reading specific entries.
See also
DenseCoeffsBase<Derived, DirectAccessors>, The class hierarchy
Public Member Functions
CoeffReturnType coeff (Index row, Index col) const
CoeffReturnType coeff (Index index) const
Scalar & coeffRef (Index row, Index col)
Scalar & coeffRef (Index index)
Index cols () const
Derived & derived ()
const Derived & derived () const
CoeffReturnType operator() (Index row, Index col) const
CoeffReturnType operator() (Index index) const
Scalar & operator() (Index row, Index col)
Scalar & operator() (Index index)
CoeffReturnType operator[] (Index index) const
Scalar & operator[] (Index index)
Index rows () const
Index size () const
CoeffReturnType w () const
Scalar & w ()
CoeffReturnType x () const
Scalar & x ()
CoeffReturnType y () const
Scalar & y ()
CoeffReturnType z () const
Scalar & z ()
Member Function Documentation
coeff() [1/2]
CoeffReturnType coeff (Index row, Index col) const inline inherited
Short version: don't use this function, use operator()(Index,Index) const instead.
Long version: this function is similar to operator()(Index,Index) const , but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameters row and col are in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator()(Index,Index) const .
See also
operator()(Index,Index) const, coeffRef(Index,Index), coeff(Index) const
coeff() [2/2]
CoeffReturnType coeff (Index index) const inline inherited
Short version: don't use this function, use operator[](Index) const instead.
Long version: this function is similar to operator[](Index) const , but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameter index is in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator[](Index) const .
See also
operator[](Index) const, coeffRef(Index), coeff(Index,Index) const
coeffRef() [1/2]
Scalar& coeffRef (Index row, Index col) inline
Short version: don't use this function, use operator()(Index,Index) instead.
Long version: this function is similar to operator()(Index,Index), but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameters row and col are in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator()(Index,Index).
See also
operator()(Index,Index), coeff(Index, Index) const, coeffRef(Index)
coeffRef() [2/2]
Scalar& coeffRef (Index index) inline
Short version: don't use this function, use operator[](Index) instead.
Long version: this function is similar to operator[](Index), but without the assertion. Use this for limiting the performance cost of debugging code when doing repeated coefficient access. Only use this when it is guaranteed that the parameters row and col are in range.
If EIGEN_INTERNAL_DEBUGGING is defined, an assertion will be made, making this function equivalent to operator[](Index).
See also
operator[](Index), coeff(Index) const, coeffRef(Index,Index)
cols()
Index cols (void) const inline inherited
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), and EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size().
derived() [1/2]
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::analyzePattern(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheLeft(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRightCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRows(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::compute(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::factorize(), SparseQR< _MatrixType, _OrderingType >::factorize(), PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::indices(), PermutationWrapper< _IndicesType >::indices(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::IterativeSolverBase(), SparseVector< _Scalar, _Options, _Index >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator*(), RotationBase< Derived, 3 >::operator*(), SparseSelfAdjointView< MatrixType, UpLo >::operator*(), Translation< _Scalar, _Dim >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator*=(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator=(), DenseBase< Derived >::operator=(), Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SparseMatrix< Scalar, RowMajor >::setFromTriplets(), SparseMatrix< Scalar, RowMajor >::setIdentity(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), SparseLU< _MatrixType, _OrderingType >::solve(), SparseQR< _MatrixType, _OrderingType >::solve(), UmfPackLU< _MatrixType >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), SparseVector< _Scalar, _Options, _Index >::swap(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topRightCorner(), Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
derived() [2/2]
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
operator()() [1/4]
CoeffReturnType operator() (Index row, Index col) const inline inherited
Returns
the coefficient at given the given row and column.
See also
operator()(Index,Index), operator[](Index)
operator()() [2/4]
CoeffReturnType operator() (Index index) const inline inherited
Returns
the coefficient at given index.
This is synonymous to operator[](Index) const.
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See also
operator[](Index), operator()(Index,Index) const, x() const, y() const, z() const, w() const
operator()() [3/4]
Scalar& operator() (Index row, Index col) inline
Returns
a reference to the coefficient at given the given row and column.
See also
operator[](Index)
operator()() [4/4]
Scalar& operator() (Index index) inline
Returns
a reference to the coefficient at given index.
This is synonymous to operator[](Index).
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See also
operator[](Index) const, operator()(Index,Index), x(), y(), z(), w()
operator[]() [1/2]
CoeffReturnType operator[] (Index index) const inline inherited
Returns
the coefficient at given index.
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See also
operator[](Index), operator()(Index,Index) const, x() const, y() const, z() const, w() const
operator[]() [2/2]
Scalar& operator[] (Index index) inline
Returns
a reference to the coefficient at given index.
This method is allowed only for vector expressions, and for matrix expressions having the LinearAccessBit.
See also
operator[](Index) const, operator()(Index,Index), x(), y(), z(), w()
rows()
Index rows (void) const inline inherited
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), and EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size().
size()
Index size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase().
w() [1/2]
CoeffReturnType w () const inline inherited
equivalent to operator[](3).
w() [2/2]
Scalar& w () inline
equivalent to operator[](3).
x() [1/2]
CoeffReturnType x () const inline inherited
equivalent to operator[](0).
x() [2/2]
Scalar& x () inline
equivalent to operator[](0).
y() [1/2]
CoeffReturnType y () const inline inherited
equivalent to operator[](1).
y() [2/2]
Scalar& y () inline
equivalent to operator[](1).
z() [1/2]
CoeffReturnType z () const inline inherited
equivalent to operator[](2).
z() [2/2]
Scalar& z () inline
equivalent to operator[](2).
The documentation for this class was generated from the following file:
DenseCoeffsBase.h