Eigen: SparseSelfAdjointView< MatrixType, UpLo > Class Template Reference
SparseSelfAdjointView< MatrixType, UpLo > Class Template Reference
Sparse linear algebra » Reference » SparseCore_Module
Detailed Description
template<typename MatrixType, unsigned int UpLo>
class Eigen::SparseSelfAdjointView< MatrixType, UpLo >
Pseudo expression to manipulate a triangular sparse matrix as a selfadjoint matrix.
Parameters
MatrixType the type of the dense matrix storing the coefficients
UpLo can be either #Lower or #Upper
This class is an expression of a sefladjoint matrix from a triangular part of a matrix with given dense storage of the coefficients. It is the return type of MatrixBase::selfadjointView() and most of the time this is the only way that it is used.
See also
SparseMatrixBase::selfadjointView()
Public Member Functions
SparseSelfAdjointView< MatrixType, UpLo > & derived ()
const SparseSelfAdjointView< MatrixType, UpLo > & derived () const
template<typename OtherDerived >
SparseSparseProduct< typename OtherDerived::PlainObject, OtherDerived > operator* (const SparseMatrixBase< OtherDerived > &rhs) const
template<typename OtherDerived >
SparseSelfAdjointTimeDenseProduct< MatrixType, OtherDerived, UpLo > operator* (const MatrixBase< OtherDerived > &rhs) const
template<typename DerivedU >
SparseSelfAdjointView & rankUpdate (const SparseMatrixBase< DerivedU > &u, const Scalar &alpha=Scalar(1))
Index size () const
SparseSymmetricPermutationProduct< _MatrixTypeNested, UpLo > twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > &perm) const
Friends
template<typename OtherDerived >
SparseSparseProduct< OtherDerived, typename OtherDerived::PlainObject > operator* (const SparseMatrixBase< OtherDerived > &lhs, const SparseSelfAdjointView &rhs)
template<typename OtherDerived >
DenseTimeSparseSelfAdjointProduct< OtherDerived, MatrixType, UpLo > operator* (const MatrixBase< OtherDerived > &lhs, const SparseSelfAdjointView &rhs)
Member Function Documentation
derived() [1/2]
SparseSelfAdjointView< MatrixType, UpLo > & derived () inline inherited
Returns
a reference to the derived object
derived() [2/2]
const SparseSelfAdjointView< MatrixType, UpLo > & derived () const inline inherited
Returns
a const reference to the derived object
operator*() [1/2]
SparseSparseProduct<typename OtherDerived::PlainObject, OtherDerived> operator* (const SparseMatrixBase< OtherDerived > & rhs) const inline
Returns
an expression of the matrix product between a sparse self-adjoint matrix *this and a sparse matrix rhs.
Note that there is no algorithmic advantage of performing such a product compared to a general sparse-sparse matrix product. Indeed, the SparseSelfadjointView operand is first copied into a temporary SparseMatrix before computing the product.
References EigenBase< Derived >::derived().
operator*() [2/2]
SparseSelfAdjointTimeDenseProduct<MatrixType,OtherDerived,UpLo> operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient sparse self-adjoint matrix times dense vector/matrix product
rankUpdate()
SparseSelfAdjointView& rankUpdate (const SparseMatrixBase< DerivedU > & u, const Scalar & alpha = Scalar(1))
Perform a symmetric rank K update of the selfadjoint matrix *this: where u is a vector or matrix.
Returns
a reference to *this
To perform you can simply call this function with u.adjoint().
Referenced by SparseSelfAdjointView< MatrixType, UpLo >::twistedBy().
size()
Index size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
twistedBy()
SparseSymmetricPermutationProduct<_MatrixTypeNested,UpLo> twistedBy (const PermutationMatrix< Dynamic, Dynamic, Index > & perm) const inline
Returns
an expression of P H P^-1
References Eigen::ColMajor, EigenBase< SparseMatrix< _Scalar, _Options, _Index > >::derived(), Eigen::Lower, SparseSelfAdjointView< MatrixType, UpLo >::rankUpdate(), PlainObjectBase< Derived >::resize(), Eigen::RowMajor, Eigen::RowMajorBit, PlainObjectBase< Derived >::setZero(), SparseSelfAdjointView< MatrixType, UpLo >::twistedBy(), and Eigen::Upper.
Referenced by SparseSelfAdjointView< MatrixType, UpLo >::twistedBy().
Friends And Related Function Documentation
operator* [1/2]
SparseSparseProduct<OtherDerived, typename OtherDerived::PlainObject > operator* (const SparseMatrixBase< OtherDerived > & lhs, const SparseSelfAdjointView< MatrixType, UpLo > & rhs) friend
Returns
an expression of the matrix product between a sparse matrix lhs and a sparse self-adjoint matrix rhs.
Note that there is no algorithmic advantage of performing such a product compared to a general sparse-sparse matrix product. Indeed, the SparseSelfadjointView operand is first copied into a temporary SparseMatrix before computing the product.
operator* [2/2]
DenseTimeSparseSelfAdjointProduct<OtherDerived,MatrixType,UpLo> operator* (const MatrixBase< OtherDerived > & lhs, const SparseSelfAdjointView< MatrixType, UpLo > & rhs) friend
Efficient dense vector/matrix times sparse self-adjoint matrix product
The documentation for this class was generated from the following file:
SparseSelfAdjointView.h