Eigen: GeneralizedEigenSolver< _MatrixType > Class Template Reference
GeneralizedEigenSolver< _MatrixType > Class Template Reference
Dense linear problems and decompositions » Reference » Eigenvalues_Module
Detailed Description
template<typename _MatrixType>
class Eigen::GeneralizedEigenSolver< _MatrixType >
Computes the generalized eigenvalues and eigenvectors of a pair of general matrices.
This is defined in the Eigenvalues module.
#include <Eigen/Eigenvalues>
Template Parameters
_MatrixType the type of the matrices of which we are computing the eigen-decomposition; this is expected to be an instantiation of the Matrix class template. Currently, only real matrices are supported.
The generalized eigenvalues and eigenvectors of a matrix pair and are scalars and vectors such that . If is a diagonal matrix with the eigenvalues on the diagonal, and is a matrix with the eigenvectors as its columns, then . The matrix is almost always invertible, in which case we have . This is called the generalized eigen-decomposition.
The generalized eigenvalues and eigenvectors of a matrix pair may be complex, even when the matrices are real. Moreover, the generalized eigenvalue might be infinite if the matrix B is singular. To workaround this difficulty, the eigenvalues are provided as a pair of complex and real such that: . If is (nearly) zero, then one can consider the well defined left eigenvalue such that: , or even where is called the left eigenvector.
Call the function compute() to compute the generalized eigenvalues and eigenvectors of a given matrix pair. Alternatively, you can use the GeneralizedEigenSolver(const MatrixType&, const MatrixType&, bool) constructor which computes the eigenvalues and eigenvectors at construction time. Once the eigenvalue and eigenvectors are computed, they can be retrieved with the eigenvalues() and eigenvectors() functions.
Here is an usage example of this class: Example:
GeneralizedEigenSolver<MatrixXf> ges;
MatrixXf A = MatrixXf::Random(4,4);
MatrixXf B = MatrixXf::Random(4,4);
ges.compute(A, B);
cout << "The (complex) numerators of the generalzied eigenvalues are: " << ges.alphas().transpose() << endl;
cout << "The (real) denominatore of the generalzied eigenvalues are: " << ges.betas().transpose() << endl;
cout << "The (complex) generalzied eigenvalues are (alphas./beta): " << ges.eigenvalues().transpose() << endl;
Output:
The (complex) numerators of the generalzied eigenvalues are:  (0.322,1.45) (0.322,-1.45)    (-0.398,0)     (-1.12,0)
The (real) denominatore of the generalzied eigenvalues are:  3.97  3.97 -1.25 0.746
The (complex) generalzied eigenvalues are (alphas./beta):  (0.081,0.365) (0.081,-0.365)     (0.318,-0)       (-1.5,0)
See also
MatrixBase::eigenvalues(), class ComplexEigenSolver, class SelfAdjointEigenSolver
Public Types
typedef std::complex< RealScalar > ComplexScalar
Complex scalar type for MatrixType.
typedef Matrix< ComplexScalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > ComplexVectorType
Type for vector of complex scalar values eigenvalues as returned by betas().
typedef CwiseBinaryOp< internal::scalar_quotient_op< ComplexScalar, Scalar >, ComplexVectorType, VectorType > EigenvalueType
Expression type for the eigenvalues as returned by eigenvalues().
typedef Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime > EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
typedef _MatrixType MatrixType
Synonym for the template parameter _MatrixType.
typedef MatrixType::Scalar Scalar
Scalar type for matrices of type MatrixType.
typedef Matrix< Scalar, ColsAtCompileTime, 1, Options &~RowMajor, MaxColsAtCompileTime, 1 > VectorType
Type for vector of real scalar values eigenvalues as returned by betas().
Public Member Functions
ComplexVectorType alphas () const
VectorType betas () const
GeneralizedEigenSolver & compute (const MatrixType &A, const MatrixType &B, bool computeEigenvectors=true)
Computes generalized eigendecomposition of given matrix.
EigenvalueType eigenvalues () const
Returns an expression of the computed generalized eigenvalues.
GeneralizedEigenSolver ()
Default constructor.
GeneralizedEigenSolver (Index size)
Default constructor with memory preallocation.
GeneralizedEigenSolver (const MatrixType &A, const MatrixType &B, bool computeEigenvectors=true)
Constructor; computes the generalized eigendecomposition of given matrix pair.
GeneralizedEigenSolver & setMaxIterations (Index maxIters)
Member Typedef Documentation
ComplexScalar
typedef std::complex<RealScalar> ComplexScalar
Complex scalar type for MatrixType.
This is std::complex<Scalar> if Scalar is real (e.g., float or double) and just Scalar if Scalar is complex.
ComplexVectorType
typedef Matrix<ComplexScalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> ComplexVectorType
Type for vector of complex scalar values eigenvalues as returned by betas().
This is a column vector with entries of type ComplexScalar. The length of the vector is the size of MatrixType.
EigenvectorsType
typedef Matrix<ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime> EigenvectorsType
Type for matrix of eigenvectors as returned by eigenvectors().
This is a square matrix with entries of type ComplexScalar. The size is the same as the size of MatrixType.
VectorType
typedef Matrix<Scalar, ColsAtCompileTime, 1, Options & ~RowMajor, MaxColsAtCompileTime, 1> VectorType
Type for vector of real scalar values eigenvalues as returned by betas().
This is a column vector with entries of type Scalar. The length of the vector is the size of MatrixType.
Constructor & Destructor Documentation
GeneralizedEigenSolver() [1/3]
GeneralizedEigenSolver () inline
Default constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via EigenSolver::compute(const MatrixType&, bool).
See also
compute() for an example.
GeneralizedEigenSolver() [2/3]
GeneralizedEigenSolver (Index size) inline
Default constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
GeneralizedEigenSolver()
GeneralizedEigenSolver() [3/3]
GeneralizedEigenSolver (const MatrixType & A, const MatrixType & B, bool computeEigenvectors = true) inline
Constructor; computes the generalized eigendecomposition of given matrix pair.
Parameters
[in] A Square matrix whose eigendecomposition is to be computed.
[in] B Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
This constructor calls compute() to compute the generalized eigenvalues and eigenvectors.
See also
compute()
References GeneralizedEigenSolver< _MatrixType >::compute().
Member Function Documentation
alphas()
ComplexVectorType alphas () const inline
Returns
A const reference to the vectors containing the alpha values
This vector permits to reconstruct the j-th eigenvalues as alphas(i)/betas(j).
See also
betas(), eigenvalues()
betas()
VectorType betas () const inline
Returns
A const reference to the vectors containing the beta values
This vector permits to reconstruct the j-th eigenvalues as alphas(i)/betas(j).
See also
alphas(), eigenvalues()
References GeneralizedEigenSolver< _MatrixType >::compute(), and RealQZ< _MatrixType >::info().
compute()
GeneralizedEigenSolver< MatrixType > & compute (const MatrixType & A, const MatrixType & B, bool computeEigenvectors = true)
Computes generalized eigendecomposition of given matrix.
Parameters
[in] A Square matrix whose eigendecomposition is to be computed.
[in] B Square matrix whose eigendecomposition is to be computed.
[in] computeEigenvectors If true, both the eigenvectors and the eigenvalues are computed; if false, only the eigenvalues are computed.
Returns
Reference to *this
This function computes the eigenvalues of the real matrix matrix. The eigenvalues() function can be used to retrieve them. If computeEigenvectors is true, then the eigenvectors are also computed and can be retrieved by calling eigenvectors().
The matrix is first reduced to real generalized Schur form using the RealQZ class. The generalized Schur decomposition is then used to compute the eigenvalues and eigenvectors.
The cost of the computation is dominated by the cost of the generalized Schur decomposition.
This method reuses of the allocated data in the GeneralizedEigenSolver object.
References RealQZ< _MatrixType >::compute(), RealQZ< _MatrixType >::info(), RealQZ< _MatrixType >::matrixS(), RealQZ< _MatrixType >::matrixT(), RealQZ< _MatrixType >::matrixZ(), PlainObjectBase< Derived >::resize(), and Eigen::Success.
Referenced by GeneralizedEigenSolver< _MatrixType >::betas(), and GeneralizedEigenSolver< _MatrixType >::GeneralizedEigenSolver().
eigenvalues()
EigenvalueType eigenvalues () const inline
Returns an expression of the computed generalized eigenvalues.
Returns
An expression of the column vector containing the eigenvalues.
It is a shortcut for
this->alphas().cwiseQuotient(this->betas());
Not that betas might contain zeros. It is therefore not recommended to use this function, but rather directly deal with the alphas and betas vectors.
Precondition
Either the constructor GeneralizedEigenSolver(const MatrixType&,const MatrixType&,bool) or the member function compute(const MatrixType&,const MatrixType&,bool) has been called before.
The eigenvalues are repeated according to their algebraic multiplicity, so there are as many eigenvalues as rows in the matrix. The eigenvalues are not sorted in any particular order.
See also
alphas(), betas(), eigenvectors()
setMaxIterations()
GeneralizedEigenSolver& setMaxIterations (Index maxIters) inline
Sets the maximal number of iterations allowed.
References RealQZ< _MatrixType >::setMaxIterations().
The documentation for this class was generated from the following file:
GeneralizedEigenSolver.h