Eigen: PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > Class Template Reference
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Detailed Description
template<int SizeAtCompileTime, int MaxSizeAtCompileTime, typename IndexType>
class Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >
Permutation matrix.
Parameters
SizeAtCompileTime the number of rows/cols, or Dynamic
MaxSizeAtCompileTime the maximum number of rows/cols, or Dynamic. This optional parameter defaults to SizeAtCompileTime. Most of the time, you should not have to specify it.
IndexType the interger type of the indices
This class represents a permutation matrix, internally stored as a vector of integers.
See also
class PermutationBase, class PermutationWrapper, class DiagonalMatrix
Public Member Functions
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & applyTranspositionOnTheLeft (Index i, Index j)
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & applyTranspositionOnTheRight (Index i, Index j)
Index cols () const
Derived & derived ()
const Derived & derived () const
Index determinant () const
const IndicesType & indices () const
IndicesType & indices ()
Transpose< PermutationBase > inverse () const
PlainPermutationType operator* (const PermutationBase< Other > &other) const
PlainPermutationType operator* (const Transpose< PermutationBase< Other > > &other) const
template<typename Other >
PermutationMatrix & operator= (const PermutationBase< Other > &other)
template<typename Other >
PermutationMatrix & operator= (const TranspositionsBase< Other > &tr)
PermutationMatrix (int size)
template<typename OtherDerived >
PermutationMatrix (const PermutationBase< OtherDerived > &other)
template<typename Other >
PermutationMatrix (const MatrixBase< Other > &a_indices)
template<typename Other >
PermutationMatrix (const TranspositionsBase< Other > &tr)
void resize (Index newSize)
Index rows () const
void setIdentity ()
void setIdentity (Index newSize)
Index size () const
DenseMatrixType toDenseMatrix () const
Transpose< PermutationBase > transpose () const
Constructor & Destructor Documentation
PermutationMatrix() [1/4]
PermutationMatrix (int size) inline
Constructs an uninitialized permutation matrix of given size.
PermutationMatrix() [2/4]
PermutationMatrix (const PermutationBase< OtherDerived > & other) inline
Copy constructor.
PermutationMatrix() [3/4]
PermutationMatrix (const MatrixBase< Other > & a_indices) inline explicit
Generic constructor from expression of the indices. The indices array has the meaning that the permutations sends each integer i to indices[i].
Warning
It is your responsibility to check that the indices array that you passes actually describes a permutation, i.e., each value between 0 and n-1 occurs exactly once, where n is the array's size.
PermutationMatrix() [4/4]
PermutationMatrix (const TranspositionsBase< Other > & tr) inline explicit
Convert the Transpositions tr to a permutation matrix
Member Function Documentation
applyTranspositionOnTheLeft()
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & applyTranspositionOnTheLeft (Index i, Index j) inline inherited
Multiplies *this by the transposition on the left.
Returns
a reference to *this.
Warning
This is much slower than applyTranspositionOnTheRight(int,int): this has linear complexity and requires a lot of branching.
See also
applyTranspositionOnTheRight(int,int)
applyTranspositionOnTheRight()
PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > & applyTranspositionOnTheRight (Index i, Index j) inline inherited
Multiplies *this by the transposition on the right.
Returns
a reference to *this.
This is a fast operation, it only consists in swapping two indices.
See also
applyTranspositionOnTheLeft(int,int)
cols()
Index cols (void) const inline inherited
Returns
the number of columns
derived() [1/2]
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::analyzePattern(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheLeft(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRightCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRows(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::compute(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::factorize(), SparseQR< _MatrixType, _OrderingType >::factorize(), PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::indices(), PermutationWrapper< _IndicesType >::indices(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::IterativeSolverBase(), SparseVector< _Scalar, _Options, _Index >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator*(), RotationBase< Derived, 3 >::operator*(), SparseSelfAdjointView< MatrixType, UpLo >::operator*(), Translation< _Scalar, _Dim >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator*=(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator=(), DenseBase< Derived >::operator=(), Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SparseMatrix< Scalar, RowMajor >::setFromTriplets(), SparseMatrix< Scalar, RowMajor >::setIdentity(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), SparseLU< _MatrixType, _OrderingType >::solve(), SparseQR< _MatrixType, _OrderingType >::solve(), UmfPackLU< _MatrixType >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), SparseVector< _Scalar, _Options, _Index >::swap(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topRightCorner(), Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
derived() [2/2]
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
determinant()
Index determinant () const inline inherited
Returns
the determinant of the permutation matrix, which is either 1 or -1 depending on the parity of the permutation.
This function is O(n) procedure allocating a buffer of n booleans.
References DenseBase< Derived >::fill().
indices() [1/2]
const IndicesType& indices () const inline
const version of indices().
Referenced by SparseLU< _MatrixType, _OrderingType >::analyzePattern(), SPQR< _MatrixType >::colsPermutation(), SparseLU< _MatrixType, _OrderingType >::factorize(), PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::indices(), COLAMDOrdering< Index >::operator()(), and PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::PermutationMatrix().
indices() [2/2]
IndicesType& indices () inline
Returns
a reference to the stored array representing the permutation.
inverse()
Transpose<PermutationBase> inverse () const inline inherited
Returns
the inverse permutation matrix.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
operator*() [1/2]
PlainPermutationType operator* (const PermutationBase< Other > & other) const inline inherited
Returns
the product permutation matrix.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
References EigenBase< Derived >::derived().
operator*() [2/2]
PlainPermutationType operator* (const Transpose< PermutationBase< Other > > & other) const inline inherited
Returns
the product of a permutation with another inverse permutation.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
operator=() [1/2]
PermutationMatrix& operator= (const PermutationBase< Other > & other) inline
Copies the other permutation into *this
operator=() [2/2]
PermutationMatrix& operator= (const TranspositionsBase< Other > & tr) inline
Assignment from the Transpositions tr
resize()
void resize (Index newSize) inline inherited
Resizes to given size.
rows()
Index rows (void) const inline inherited
Returns
the number of rows
setIdentity() [1/2]
void setIdentity () inline inherited
Sets *this to be the identity permutation matrix
setIdentity() [2/2]
void setIdentity (Index newSize) inline inherited
Sets *this to be the identity permutation matrix of given size.
size()
Index size () const inline inherited
Returns
the size of a side of the respective square matrix, i.e., the number of indices
References DenseBase< Derived >::setZero(), and PermutationBase< Derived >::size().
toDenseMatrix()
DenseMatrixType toDenseMatrix () const inline inherited
Returns
a Matrix object initialized from this permutation matrix. Notice that it is inefficient to return this Matrix object by value. For efficiency, favor using the Matrix constructor taking EigenBase objects.
transpose()
Transpose<PermutationBase> transpose () const inline inherited
Returns
the tranpose permutation matrix.
Note
This function returns the result by value. In order to make that efficient, it is implemented as just a return statement using a special constructor, hopefully allowing the compiler to perform a RVO (return value optimization).
References PermutationBase< Derived >::indices().
The documentation for this class was generated from the following file:
PermutationMatrix.h