Eigen: Translation< _Scalar, _Dim > Class Template Reference
Translation< _Scalar, _Dim > Class Template Reference
Geometry » Reference » Geometry_Module
Detailed Description
template<typename _Scalar, int _Dim>
class Eigen::Translation< _Scalar, _Dim >
Represents a translation transformation.
This is defined in the Geometry module.
#include <Eigen/Geometry>
Parameters
_Scalar the scalar type, i.e., the type of the coefficients.
_Dim the dimension of the space, can be a compile time value or Dynamic
Note
This class is not aimed to be used to store a translation transformation, but rather to make easier the constructions and updates of Transform objects.
See also
class Scaling, class Transform
Public Types
enum
typedef Transform< Scalar, Dim, Affine > AffineTransformType
typedef Transform< Scalar, Dim, Isometry > IsometryTransformType
typedef Matrix< Scalar, Dim, Dim > LinearMatrixType
typedef _Scalar Scalar
typedef Matrix< Scalar, Dim, 1 > VectorType
Public Member Functions
template<typename NewScalarType >
internal::cast_return_type< Translation, Translation< NewScalarType, Dim > >::type cast () const
Translation inverse () const
bool isApprox (const Translation &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
Translation operator* (const Translation &other) const
AffineTransformType operator* (const UniformScaling< Scalar > &other) const
template<typename OtherDerived >
AffineTransformType operator* (const EigenBase< OtherDerived > &linear) const
template<typename Derived >
IsometryTransformType operator* (const RotationBase< Derived, Dim > &r) const
template<int Mode, int Options>
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
template<typename Derived >
internal::enable_if< Derived::IsVectorAtCompileTime, VectorType >::type operator* (const MatrixBase< Derived > &vec) const
Translation ()
Translation (const VectorType &vector)
template<typename OtherScalarType >
Translation (const Translation< OtherScalarType, Dim > &other)
Scalar x () const
Retruns the x-translation by value.
Scalar & x ()
Retruns the x-translation as a reference.
Scalar y () const
Retruns the y-translation by value.
Scalar & y ()
Retruns the y-translation as a reference.
Scalar z () const
Retruns the z-translation by value.
Scalar & z ()
Retruns the z-translation as a reference.
Friends
template<typename OtherDerived >
AffineTransformType operator* (const EigenBase< OtherDerived > &linear, const Translation &t)
Member Typedef Documentation
AffineTransformType
typedef Transform<Scalar,Dim,Affine> AffineTransformType
corresponding affine transformation type
IsometryTransformType
typedef Transform<Scalar,Dim,Isometry> IsometryTransformType
corresponding isometric transformation type
LinearMatrixType
typedef Matrix<Scalar,Dim,Dim> LinearMatrixType
corresponding linear transformation matrix type
Scalar
typedef _Scalar Scalar
the scalar type of the coefficients
VectorType
typedef Matrix<Scalar,Dim,1> VectorType
corresponding vector type
Member Enumeration Documentation
anonymous enum
anonymous enum
dimension of the space
Constructor & Destructor Documentation
Translation() [1/3]
Translation () inline
Default constructor without initialization.
Referenced by Translation< _Scalar, _Dim >::inverse(), and Translation< _Scalar, _Dim >::operator*().
Translation() [2/3]
Translation (const VectorType & vector) inline explicit
Constructs and initialize the translation transformation from a vector of translation coefficients
Translation() [3/3]
Translation (const Translation< OtherScalarType, Dim > & other) inline explicit
Copy constructor with scalar type conversion
Member Function Documentation
cast()
internal::cast_return_type<Translation,Translation<NewScalarType,Dim> >::type cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
inverse()
Translation inverse () const inline
Returns
the inverse translation (opposite)
References Translation< _Scalar, _Dim >::Translation().
isApprox()
bool isApprox (const Translation< _Scalar, _Dim > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
operator*() [1/6]
Translation operator* (const Translation< _Scalar, _Dim > & other) const inline
Concatenates two translation
References Translation< _Scalar, _Dim >::Translation().
operator*() [2/6]
Translation< Scalar, Dim >::AffineTransformType operator* (const UniformScaling< Scalar > & other) const inline
Concatenates a translation and a uniform scaling
References Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), PlainObjectBase< Derived >::setZero(), and Transform< _Scalar, _Dim, _Mode, _Options >::translation().
operator*() [3/6]
Translation< Scalar, Dim >::AffineTransformType operator* (const EigenBase< OtherDerived > & linear) const inline
Concatenates a translation and a linear transformation
References EigenBase< Derived >::derived(), Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), DenseBase< Derived >::row(), PlainObjectBase< Derived >::setZero(), and Transform< _Scalar, _Dim, _Mode, _Options >::translation().
operator*() [4/6]
IsometryTransformType operator* (const RotationBase< Derived, Dim > & r) const inline
Concatenates a translation and a rotation
operator*() [5/6]
Transform<Scalar,Dim,Mode> operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline
Concatenates a translation and a transformation
operator*() [6/6]
internal::enable_if<Derived::IsVectorAtCompileTime,VectorType>::type operator* (const MatrixBase< Derived > & vec) const inline
Applies translation to vector
Friends And Related Function Documentation
operator*
AffineTransformType operator* (const EigenBase< OtherDerived > & linear, const Translation< _Scalar, _Dim > & t) friend
Returns
the concatenation of a linear transformation l with the translation t
The documentation for this class was generated from the following files:
ForwardDeclarations.h
Translation.h