Eigen: NoAlias< ExpressionType, StorageBase > Class Template Reference
NoAlias< ExpressionType, StorageBase > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Detailed Description
template<typename ExpressionType, template< typename > class StorageBase>
class Eigen::NoAlias< ExpressionType, StorageBase >
Pseudo expression providing an operator = assuming no aliasing.
Parameters
ExpressionType the type of the object on which to do the lazy assignment
This class represents an expression with special assignment operators assuming no aliasing between the target expression and the source expression. More precisely it alloas to bypass the EvalBeforeAssignBit flag of the source expression. It is the return type of MatrixBase::noalias() and most of the time this is the only way it is used.
See also
MatrixBase::noalias()
Public Member Functions
template<typename OtherDerived >
ExpressionType & operator+= (const StorageBase< OtherDerived > &other)
template<typename OtherDerived >
ExpressionType & operator-= (const StorageBase< OtherDerived > &other)
template<typename OtherDerived >
ExpressionType & operator= (const StorageBase< OtherDerived > &other)
Member Function Documentation
operator+=()
ExpressionType& operator+= (const StorageBase< OtherDerived > & other) inline
See also
MatrixBase::operator+=
Referenced by NoAlias< ExpressionType, StorageBase >::operator-=().
operator-=()
ExpressionType& operator-= (const StorageBase< OtherDerived > & other) inline
See also
MatrixBase::operator-=
References NoAlias< ExpressionType, StorageBase >::operator+=(), and NoAlias< ExpressionType, StorageBase >::operator=().
operator=()
ExpressionType& operator= (const StorageBase< OtherDerived > & other) inline
Behaves like MatrixBase::lazyAssign(other)
See also
MatrixBase::lazyAssign()
Referenced by NoAlias< ExpressionType, StorageBase >::operator-=().
The documentation for this class was generated from the following file:
NoAlias.h