Eigen: AngleAxis< _Scalar > Class Template Reference
AngleAxis< _Scalar > Class Template Reference
Geometry » Reference » Geometry_Module
Detailed Description
template<typename _Scalar>
class Eigen::AngleAxis< _Scalar >
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
This is defined in the Geometry module.
#include <Eigen/Geometry>
Parameters
_Scalar the scalar type, i.e., the type of the coefficients.
Warning
When setting up an AngleAxis object, the axis vector must be normalized.
The following two typedefs are provided for convenience:
AngleAxisf for float
AngleAxisd for double
Combined with MatrixBase::Unit{X,Y,Z}, AngleAxis can be used to easily mimic Euler-angles. Here is an example:
Matrix3f m;
m = AngleAxisf(0.25*M_PI, Vector3f::UnitX())
  * AngleAxisf(0.5*M_PI,  Vector3f::UnitY())
  * AngleAxisf(0.33*M_PI, Vector3f::UnitZ());
cout << m << endl << "is unitary: " << m.isUnitary() << endl;
Output:
1.19e-07        0        1
   0.969   -0.249        0
   0.249    0.969 1.19e-07
is unitary: 1
Note
This class is not aimed to be used to store a rotation transformation, but rather to make easier the creation of other rotation (Quaternion, rotation Matrix) and transformation objects.
See also
class Quaternion, class Transform, MatrixBase::UnitX()
Public Types
typedef Matrix< Scalar, Dim, Dim > RotationMatrixType
typedef _Scalar Scalar
Public Member Functions
Scalar angle () const
Scalar & angle ()
AngleAxis ()
template<typename Derived >
AngleAxis (const Scalar &angle, const MatrixBase< Derived > &axis)
template<typename QuatDerived >
AngleAxis (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
AngleAxis (const MatrixBase< Derived > &m)
template<typename OtherScalarType >
AngleAxis (const AngleAxis< OtherScalarType > &other)
const Vector3 & axis () const
Vector3 & axis ()
template<typename NewScalarType >
internal::cast_return_type< AngleAxis, AngleAxis< NewScalarType > >::type cast () const
template<typename Derived >
AngleAxis< Scalar > & fromRotationMatrix (const MatrixBase< Derived > &mat)
Sets *this from a 3x3 rotation matrix.
AngleAxis inverse () const
bool isApprox (const AngleAxis &other, const typename NumTraits< Scalar >::Real &prec=NumTraits< Scalar >::dummy_precision()) const
RotationMatrixType matrix () const
Transform< Scalar, Dim, Isometry > operator* (const Translation< Scalar, Dim > &t) const
RotationMatrixType operator* (const UniformScaling< Scalar > &s) const
internal::rotation_base_generic_product_selector< AngleAxis< _Scalar >, OtherDerived, OtherDerived::IsVectorAtCompileTime >::ReturnType operator* (const EigenBase< OtherDerived > &e) const
Transform< Scalar, Dim, Mode > operator* (const Transform< Scalar, Dim, Mode, Options > &t) const
QuaternionType operator* (const AngleAxis &other) const
QuaternionType operator* (const QuaternionType &other) const
template<typename QuatDerived >
AngleAxis< Scalar > & operator= (const QuaternionBase< QuatDerived > &q)
template<typename Derived >
AngleAxis< Scalar > & operator= (const MatrixBase< Derived > &mat)
Matrix3 toRotationMatrix (void) const
Friends
QuaternionType operator* (const QuaternionType &a, const AngleAxis &b)
Member Typedef Documentation
RotationMatrixType
typedef Matrix<Scalar,Dim,Dim> RotationMatrixType inherited
corresponding linear transformation matrix type
Scalar
typedef _Scalar Scalar
the scalar type of the coefficients
Constructor & Destructor Documentation
AngleAxis() [1/5]
AngleAxis () inline
Default constructor without initialization.
AngleAxis() [2/5]
AngleAxis (const Scalar & angle, const MatrixBase< Derived > & axis) inline
Constructs and initialize the angle-axis rotation from an angle in radian and an axis which must be normalized.
Warning
If the axis vector is not normalized, then the angle-axis object represents an invalid rotation.
AngleAxis() [3/5]
AngleAxis (const QuaternionBase< QuatDerived > & q) inline explicit
Constructs and initialize the angle-axis rotation from a quaternion q.
AngleAxis() [4/5]
AngleAxis (const MatrixBase< Derived > & m) inline explicit
Constructs and initialize the angle-axis rotation from a 3x3 rotation matrix.
AngleAxis() [5/5]
AngleAxis (const AngleAxis< OtherScalarType > & other) inline explicit
Copy constructor with scalar type conversion
Member Function Documentation
angle() [1/2]
Scalar angle () const inline
Returns
the value of the rotation angle in radian
Referenced by QuaternionBase< Quaternion< _Scalar, _Options > >::operator=().
angle() [2/2]
Scalar& angle () inline
Returns
a read-write reference to the stored angle in radian
axis() [1/2]
const Vector3& axis () const inline
Returns
the rotation axis
Referenced by QuaternionBase< Quaternion< _Scalar, _Options > >::operator=().
axis() [2/2]
Vector3& axis () inline
Returns
a read-write reference to the stored rotation axis.
Warning
The rotation axis must remain a unit vector.
cast()
internal::cast_return_type<AngleAxis,AngleAxis<NewScalarType> >::type cast () const inline
Returns
*this with scalar type casted to NewScalarType
Note that if NewScalarType is equal to the current scalar type of *this then this function smartly returns a const reference to *this.
inverse()
AngleAxis inverse () const inline
Returns
the inverse rotation, i.e., an angle-axis with opposite rotation angle
isApprox()
bool isApprox (const AngleAxis< _Scalar > & other, const typename NumTraits< Scalar >::Real & prec = NumTraits<Scalar>::dummy_precision()) const inline
Returns
true if *this is approximately equal to other, within the precision determined by prec.
See also
MatrixBase::isApprox()
matrix()
RotationMatrixType matrix () const inline inherited
Returns
an equivalent rotation matrix This function is added to be conform with the Transform class' naming scheme.
operator*() [1/6]
Transform<Scalar,Dim,Isometry> operator* (const Translation< Scalar, Dim > & t) const inline inherited
Returns
the concatenation of the rotation *this with a translation t
operator*() [2/6]
RotationMatrixType operator* (const UniformScaling< Scalar > & s) const inline inherited
Returns
the concatenation of the rotation *this with a uniform scaling s
operator*() [3/6]
internal::rotation_base_generic_product_selector<AngleAxis< _Scalar > ,OtherDerived,OtherDerived::IsVectorAtCompileTime>::ReturnType operator* (const EigenBase< OtherDerived > & e) const inline inherited
Returns
the concatenation of the rotation *this with a generic expression e e can be:
a DimxDim linear transformation matrix
a DimxDim diagonal matrix (axis aligned scaling)
a vector of size Dim
operator*() [4/6]
Transform<Scalar,Dim,Mode> operator* (const Transform< Scalar, Dim, Mode, Options > & t) const inline inherited
Returns
the concatenation of the rotation *this with a transformation t
operator*() [5/6]
QuaternionType operator* (const AngleAxis< _Scalar > & other) const inline
Concatenates two rotations
operator*() [6/6]
QuaternionType operator* (const QuaternionType & other) const inline
Concatenates two rotations
operator=() [1/2]
AngleAxis<Scalar>& operator= (const QuaternionBase< QuatDerived > & q)
Set *this from a unit quaternion. The axis is normalized.
Warning
As any other method dealing with quaternion, if the input quaternion is not normalized then the result is undefined.
References QuaternionBase< Derived >::vec(), and QuaternionBase< Derived >::w().
operator=() [2/2]
AngleAxis<Scalar>& operator= (const MatrixBase< Derived > & mat)
Set *this from a 3x3 rotation matrix mat.
toRotationMatrix()
AngleAxis< Scalar >::Matrix3 toRotationMatrix (void) const
Constructs and
Returns
an equivalent 3x3 rotation matrix.
References MatrixBase< Derived >::diagonal().
Friends And Related Function Documentation
operator*
QuaternionType operator* (const QuaternionType & a, const AngleAxis< _Scalar > & b) friend
Concatenates two rotations
The documentation for this class was generated from the following files:
ForwardDeclarations.h
AngleAxis.h