Eigen: DenseBase< Derived > Class Template Reference
DenseBase< Derived > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Detailed Description
template<typename Derived>
class Eigen::DenseBase< Derived >
Base class for all dense matrices, vectors, and arrays.
This class is the base that is inherited by all dense objects (matrix, vector, arrays, and related expression types). The common Eigen API for dense objects is contained in this class.
Template Parameters
Derived is the derived type, e.g., a matrix type or an expression.
This class can be extended with the help of the plugin mechanism described on the page Customizing/Extending Eigen by defining the preprocessor symbol EIGEN_DENSEBASE_PLUGIN.
See also
The class hierarchy
Public Types
enum {
RowsAtCompileTime,
ColsAtCompileTime,
SizeAtCompileTime,
MaxRowsAtCompileTime,
MaxColsAtCompileTime,
MaxSizeAtCompileTime,
IsVectorAtCompileTime,
Flags,
IsRowMajor ,
CoeffReadCost
}
typedef internal::traits< Derived >::Index Index
The type of indices.
Public Member Functions
bool all (void) const
bool allFinite () const
bool any (void) const
Block< Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
const Block< const Derived > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows, BlockCols > block (Index startRow, Index startCol)
template<int BlockRows, int BlockCols>
const Block< const Derived, BlockRows, BlockCols > block (Index startRow, Index startCol) const
template<int BlockRows, int BlockCols>
Block< Derived, BlockRows, BlockCols > block (Index startRow, Index startCol, Index blockRows, Index blockCols)
template<int BlockRows, int BlockCols>
const Block< const Derived, BlockRows, BlockCols > block (Index startRow, Index startCol, Index blockRows, Index blockCols) const
Block< Derived > bottomLeftCorner (Index cRows, Index cCols)
const Block< const Derived > bottomLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > bottomLeftCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > bottomLeftCorner (Index cRows, Index cCols) const
Block< Derived > bottomRightCorner (Index cRows, Index cCols)
const Block< const Derived > bottomRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner ()
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > bottomRightCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > bottomRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > bottomRightCorner (Index cRows, Index cCols) const
RowsBlockXpr bottomRows (Index n)
ConstRowsBlockXpr bottomRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type bottomRows (Index n=N)
template<int N>
ConstNRowsBlockXpr< N >::Type bottomRows (Index n=N) const
ColXpr col (Index i)
ConstColXpr col (Index i) const
ConstColwiseReturnType colwise () const
ColwiseReturnType colwise ()
Index count () const
EvalReturnType eval () const
void fill (const Scalar &value)
template<unsigned int Added, unsigned int Removed>
const Flagged< Derived, Added, Removed > flagged () const
const WithFormat< Derived > format (const IOFormat &fmt) const
bool hasNaN () const
SegmentReturnType head (Index n)
ConstSegmentReturnType head (Index n) const
template<int N>
FixedSegmentReturnType< N >::Type head (Index n=N)
template<int N>
ConstFixedSegmentReturnType< N >::Type head (Index n=N) const
Index innerSize () const
template<typename OtherDerived >
bool isApprox (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isApproxToConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isConstant (const Scalar &value, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
template<typename Derived >
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real &other, const RealScalar &prec) const
template<typename OtherDerived >
bool isMuchSmallerThan (const DenseBase< OtherDerived > &other, const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isOnes (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
bool isZero (const RealScalar &prec=NumTraits< Scalar >::dummy_precision()) const
ColsBlockXpr leftCols (Index n)
ConstColsBlockXpr leftCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type leftCols (Index n=N)
template<int N>
ConstNColsBlockXpr< N >::Type leftCols (Index n=N) const
internal::traits< Derived >::Scalar maxCoeff () const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar maxCoeff (IndexType *index) const
Scalar mean () const
ColsBlockXpr middleCols (Index startCol, Index numCols)
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const
template<int N>
NColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N)
template<int N>
ConstNColsBlockXpr< N >::Type middleCols (Index startCol, Index n=N) const
RowsBlockXpr middleRows (Index startRow, Index n)
ConstRowsBlockXpr middleRows (Index startRow, Index n) const
template<int N>
NRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N)
template<int N>
ConstNRowsBlockXpr< N >::Type middleRows (Index startRow, Index n=N) const
internal::traits< Derived >::Scalar minCoeff () const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *row, IndexType *col) const
template<typename IndexType >
internal::traits< Derived >::Scalar minCoeff (IndexType *index) const
const NestByValue< Derived > nestByValue () const
Index nonZeros () const
CommaInitializer< Derived > operator<< (const Scalar &s)
template<typename OtherDerived >
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > &other)
template<typename OtherDerived >
Derived & operator= (const DenseBase< OtherDerived > &other)
Derived & operator= (const DenseBase &other)
template<typename OtherDerived >
Derived & operator= (const EigenBase< OtherDerived > &other)
Copies the generic expression other into *this.
Index outerSize () const
Scalar prod () const
template<typename Func >
internal::result_of< Func(typename internal::traits< Derived >::Scalar)>::type redux (const Func &func) const
template<int RowFactor, int ColFactor>
const Replicate< Derived, RowFactor, ColFactor > replicate () const
const ReplicateReturnType replicate (Index rowFacor, Index colFactor) const
void resize (Index newSize)
void resize (Index nbRows, Index nbCols)
ReverseReturnType reverse ()
ConstReverseReturnType reverse () const
void reverseInPlace ()
ColsBlockXpr rightCols (Index n)
ConstColsBlockXpr rightCols (Index n) const
template<int N>
NColsBlockXpr< N >::Type rightCols (Index n=N)
template<int N>
ConstNColsBlockXpr< N >::Type rightCols (Index n=N) const
RowXpr row (Index i)
ConstRowXpr row (Index i) const
ConstRowwiseReturnType rowwise () const
RowwiseReturnType rowwise ()
SegmentReturnType segment (Index start, Index n)
ConstSegmentReturnType segment (Index start, Index n) const
template<int N>
FixedSegmentReturnType< N >::Type segment (Index start, Index n=N)
template<int N>
ConstFixedSegmentReturnType< N >::Type segment (Index start, Index n=N) const
template<typename ThenDerived , typename ElseDerived >
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > &thenMatrix, const DenseBase< ElseDerived > &elseMatrix) const
template<typename ThenDerived >
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > &thenMatrix, const typename ThenDerived::Scalar &elseScalar) const
template<typename ElseDerived >
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar &thenScalar, const DenseBase< ElseDerived > &elseMatrix) const
Derived & setConstant (const Scalar &value)
Derived & setLinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setLinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
Derived & setOnes ()
Derived & setRandom ()
Derived & setZero ()
Scalar sum () const
template<typename OtherDerived >
void swap (const DenseBase< OtherDerived > &other, int=OtherDerived::ThisConstantIsPrivateInPlainObjectBase)
template<typename OtherDerived >
void swap (PlainObjectBase< OtherDerived > &other)
SegmentReturnType tail (Index n)
ConstSegmentReturnType tail (Index n) const
template<int N>
FixedSegmentReturnType< N >::Type tail (Index n=N)
template<int N>
ConstFixedSegmentReturnType< N >::Type tail (Index n=N) const
Block< Derived > topLeftCorner (Index cRows, Index cCols)
const Block< const Derived > topLeftCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner ()
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > topLeftCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topLeftCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > topLeftCorner (Index cRows, Index cCols) const
Block< Derived > topRightCorner (Index cRows, Index cCols)
const Block< const Derived > topRightCorner (Index cRows, Index cCols) const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner ()
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > topRightCorner () const
template<int CRows, int CCols>
Block< Derived, CRows, CCols > topRightCorner (Index cRows, Index cCols)
template<int CRows, int CCols>
const Block< const Derived, CRows, CCols > topRightCorner (Index cRows, Index cCols) const
RowsBlockXpr topRows (Index n)
ConstRowsBlockXpr topRows (Index n) const
template<int N>
NRowsBlockXpr< N >::Type topRows (Index n=N)
template<int N>
ConstNRowsBlockXpr< N >::Type topRows (Index n=N) const
Eigen::Transpose< Derived > transpose ()
ConstTransposeReturnType transpose () const
void transposeInPlace ()
CoeffReturnType value () const
template<typename Visitor >
void visit (Visitor &func) const
Static Public Member Functions
static const ConstantReturnType Constant (Index rows, Index cols, const Scalar &value)
static const ConstantReturnType Constant (Index size, const Scalar &value)
static const ConstantReturnType Constant (const Scalar &value)
static const SequentialLinSpacedReturnType LinSpaced (Sequential_t, Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const SequentialLinSpacedReturnType LinSpaced (Sequential_t, const Scalar &low, const Scalar &high)
Sets a linearly space vector.
static const RandomAccessLinSpacedReturnType LinSpaced (const Scalar &low, const Scalar &high)
Sets a linearly space vector.
template<typename CustomNullaryOp >
static const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (Index rows, Index cols, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (Index size, const CustomNullaryOp &func)
template<typename CustomNullaryOp >
static const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (const CustomNullaryOp &func)
static const ConstantReturnType Ones (Index rows, Index cols)
static const ConstantReturnType Ones (Index size)
static const ConstantReturnType Ones ()
static const CwiseNullaryOp< internal::scalar_random_op< Scalar >, Derived > Random (Index rows, Index cols)
static const CwiseNullaryOp< internal::scalar_random_op< Scalar >, Derived > Random (Index size)
static const CwiseNullaryOp< internal::scalar_random_op< Scalar >, Derived > Random ()
static const ConstantReturnType Zero (Index rows, Index cols)
static const ConstantReturnType Zero (Index size)
static const ConstantReturnType Zero ()
Protected Member Functions
DenseBase ()
Related Functions
(Note that these are not member functions.)
template<typename Derived >
std::ostream & operator<< (std::ostream &s, const DenseBase< Derived > &m)
Member Typedef Documentation
Index
typedef internal::traits<Derived>::Index Index
The type of indices.
To change this, #define the preprocessor symbol EIGEN_DEFAULT_DENSE_INDEX_TYPE.
See also
Preprocessor directives.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
RowsAtCompileTime
The number of rows at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), ColsAtCompileTime, SizeAtCompileTime
ColsAtCompileTime
The number of columns at compile-time. This is just a copy of the value provided by the Derived type. If a value is not known at compile-time, it is set to the Dynamic constant.
See also
MatrixBase::rows(), MatrixBase::cols(), RowsAtCompileTime, SizeAtCompileTime
SizeAtCompileTime
This is equal to the number of coefficients, i.e. the number of rows times the number of columns, or to Dynamic if this is not known at compile-time.
See also
RowsAtCompileTime, ColsAtCompileTime
MaxRowsAtCompileTime
This value is equal to the maximum possible number of rows that this expression might have. If this expression might have an arbitrarily high number of rows, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
RowsAtCompileTime, MaxColsAtCompileTime, MaxSizeAtCompileTime
MaxColsAtCompileTime
This value is equal to the maximum possible number of columns that this expression might have. If this expression might have an arbitrarily high number of columns, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
ColsAtCompileTime, MaxRowsAtCompileTime, MaxSizeAtCompileTime
MaxSizeAtCompileTime
This value is equal to the maximum possible number of coefficients that this expression might have. If this expression might have an arbitrarily high number of coefficients, this value is set to Dynamic.
This value is useful to know when evaluating an expression, in order to determine whether it is possible to avoid doing a dynamic memory allocation.
See also
SizeAtCompileTime, MaxRowsAtCompileTime, MaxColsAtCompileTime
IsVectorAtCompileTime
This is set to true if either the number of rows or the number of columns is known at compile-time to be equal to 1. Indeed, in that case, we are dealing with a column-vector (if there is only one column) or with a row-vector (if there is only one row).
Flags
This stores expression Flags flags which may or may not be inherited by new expressions constructed from this one. See the list of flags.
IsRowMajor
True if this expression has row-major storage order.
CoeffReadCost
This is a rough measure of how expensive it is to read one coefficient from this expression.
Constructor & Destructor Documentation
DenseBase()
DenseBase () inline protected
Default constructor. Do nothing.
Member Function Documentation
all()
bool all (void) const inline
Returns
true if all coefficients are true
Example:
Vector3f boxMin(Vector3f::Zero()), boxMax(Vector3f::Ones());
Vector3f p0 = Vector3f::Random(), p1 = Vector3f::Random().cwiseAbs();
// let's check if p0 and p1 are inside the axis aligned box defined by the corners boxMin,boxMax:
cout << "Is (" << p0.transpose() << ") inside the box: "
     << ((boxMin.array()<p0.array()).all() && (boxMax.array()>p0.array()).all()) << endl;
cout << "Is (" << p1.transpose() << ") inside the box: "
     << ((boxMin.array()<p1.array()).all() && (boxMax.array()>p1.array()).all()) << endl;
Output:
Is (0.68 -0.211  0.566) inside the box: 0
Is (0.597 0.823 0.605) inside the box: 1
See also
any(), Cwise::operator<()
allFinite()
bool allFinite () const inline
Returns
true if *this contains only finite numbers, i.e., no NaN and no +/-INF values.
See also
hasNaN()
any()
bool any (void) const inline
Returns
true if at least one coefficient is true
See also
all()
block() [1/6]
Block<Derived> block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
a dynamic-size expression of a block in *this.
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows the number of rows in the block
blockCols the number of columns in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block(1, 1, 2, 2):" << endl << m.block(1, 1, 2, 2) << endl;
m.block(1, 1, 2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block(1, 1, 2, 2):
-6  1
-3  0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size matrix, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set().
block() [2/6]
const Block<const Derived> block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block(Index,Index,Index,Index).
block() [3/6]
Block<Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) inline
Returns
a fixed-size expression of a block in *this.
The template parameters BlockRows and BlockCols are the number of rows and columns in the block.
Parameters
startRow the first row in the block
startCol the first column in the block
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.block<2,2>(1,1):" << endl << m.block<2,2>(1,1) << endl;
m.block<2,2>(1,1).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.block<2,2>(1,1):
-6  1
-3  0
Now the matrix m is:
 7  9 -5 -3
-2  0  0  0
 6  0  0  9
 6  6  3  9
Note
since block is a templated member, the keyword template has to be used if the matrix type is also a template parameter:
m.template block<3,3>(1,1);
See also
class Block, block(Index,Index,Index,Index)
block() [4/6]
const Block<const Derived, BlockRows, BlockCols> block (Index startRow, Index startCol) const inline
This is the const version of block<>(Index, Index).
block() [5/6]
Block<Derived, BlockRows, BlockCols> block (Index startRow, Index startCol, Index blockRows, Index blockCols) inline
Returns
an expression of a block in *this.
Template Parameters
BlockRows number of rows in block as specified at compile-time
BlockCols number of columns in block as specified at compile-time
Parameters
startRow the first row in the block
startCol the first column in the block
blockRows number of rows in block as specified at run-time
blockCols number of columns in block as specified at run-time
This function is mainly useful for blocks where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, blockRows should equal BlockRows unless BlockRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the block:" << endl << m.block<2, Dynamic>(1, 1, 2, 3) << endl;
m.block<2, Dynamic>(1, 1, 2, 3).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the block:" << endl << m.block<2, Dynamic>(1, 1, 2, 3) << endl;
m.block<2, Dynamic>(1, 1, 2, 3).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
See also
class Block, block(Index,Index,Index,Index)
block() [6/6]
const Block<const Derived, BlockRows, BlockCols> block (Index startRow, Index startCol, Index blockRows, Index blockCols) const inline
This is the const version of block<>(Index, Index, Index, Index).
bottomLeftCorner() [1/6]
Block<Derived> bottomLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner(2, 2):" << endl;
cout << m.bottomLeftCorner(2, 2) << endl;
m.bottomLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner(2, 2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See also
class Block, block(Index,Index,Index,Index)
bottomLeftCorner() [2/6]
const Block<const Derived> bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner(Index, Index).
bottomLeftCorner() [3/6]
Block<Derived, CRows, CCols> bottomLeftCorner () inline
Returns
an expression of a fixed-size bottom-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,2>():" << endl;
cout << m.bottomLeftCorner<2,2>() << endl;
m.bottomLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,2>():
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See also
class Block, block(Index,Index,Index,Index)
bottomLeftCorner() [4/6]
const Block<const Derived, CRows, CCols> bottomLeftCorner () const inline
This is the const version of bottomLeftCorner<int, int>().
bottomLeftCorner() [5/6]
Block<Derived, CRows, CCols> bottomLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomLeftCorner<2,Dynamic>(2,2):" << endl;
cout << m.bottomLeftCorner<2,Dynamic>(2,2) << endl;
m.bottomLeftCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomLeftCorner<2,Dynamic>(2,2):
 6 -3
 6  6
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  9
 0  0  3  9
See also
class Block
bottomLeftCorner() [6/6]
const Block<const Derived, CRows, CCols> bottomLeftCorner (Index cRows, Index cCols) const inline
This is the const version of bottomLeftCorner<int, int>(Index, Index).
bottomRightCorner() [1/6]
Block<Derived> bottomRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a bottom-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner(2, 2):" << endl;
cout << m.bottomRightCorner(2, 2) << endl;
m.bottomRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner(2, 2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See also
class Block, block(Index,Index,Index,Index)
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set().
bottomRightCorner() [2/6]
const Block<const Derived> bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner(Index, Index).
bottomRightCorner() [3/6]
Block<Derived, CRows, CCols> bottomRightCorner () inline
Returns
an expression of a fixed-size bottom-right corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,2>():" << endl;
cout << m.bottomRightCorner<2,2>() << endl;
m.bottomRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,2>():
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See also
class Block, block(Index,Index,Index,Index)
bottomRightCorner() [4/6]
const Block<const Derived, CRows, CCols> bottomRightCorner () const inline
This is the const version of bottomRightCorner<int, int>().
bottomRightCorner() [5/6]
Block<Derived, CRows, CCols> bottomRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a bottom-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.bottomRightCorner<2,Dynamic>(2,2):" << endl;
cout << m.bottomRightCorner<2,Dynamic>(2,2) << endl;
m.bottomRightCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.bottomRightCorner<2,Dynamic>(2,2):
0 9
3 9
Now the matrix m is:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  0
 6  6  0  0
See also
class Block
bottomRightCorner() [6/6]
const Block<const Derived, CRows, CCols> bottomRightCorner (Index cRows, Index cCols) const inline
This is the const version of bottomRightCorner<int, int>(Index, Index).
bottomRows() [1/4]
RowsBlockXpr bottomRows (Index n) inline
Returns
a block consisting of the bottom rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows(2):" << endl;
cout << a.bottomRows(2) << endl;
a.bottomRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows(2):
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See also
class Block, block(Index,Index,Index,Index)
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set().
bottomRows() [2/4]
ConstRowsBlockXpr bottomRows (Index n) const inline
This is the const version of bottomRows(Index).
bottomRows() [3/4]
NRowsBlockXpr<N>::Type bottomRows (Index n = N) inline
Returns
a block consisting of the bottom rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.bottomRows<2>():" << endl;
cout << a.bottomRows<2>() << endl;
a.bottomRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.bottomRows<2>():
 6 -3  0  9
 6  6  3  9
Now the array a is:
 7  9 -5 -3
-2 -6  1  0
 0  0  0  0
 0  0  0  0
See also
class Block, block(Index,Index,Index,Index)
bottomRows() [4/4]
ConstNRowsBlockXpr<N>::Type bottomRows (Index n = N) const inline
This is the const version of bottomRows<int>().
col() [1/2]
ColXpr col (Index i) inline
Returns
an expression of the i-th column of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.col(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 4 0
0 5 0
0 6 1
See also
row(), class Block
Referenced by MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::array(), VectorwiseOp< ExpressionType, Direction >::cross(), UmfPackLU< _MatrixType >::factorize(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::info(), Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), and SparseLU< _MatrixType, _OrderingType >::lastErrorMessage().
col() [2/2]
ConstColXpr col (Index i) const inline
This is the const version of col().
colwise() [1/2]
const DenseBase< Derived >::ConstColwiseReturnType colwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each column:" << endl << m.colwise().sum() << endl;
cout << "Here is the maximum absolute value of each column:"
     << endl << m.cwiseAbs().colwise().maxCoeff() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the sum of each column:
  1.04  0.815 -0.238
Here is the maximum absolute value of each column:
 0.68 0.823 0.536
See also
rowwise(), class VectorwiseOp, Reductions, visitors and broadcasting
Referenced by Eigen::umeyama().
colwise() [2/2]
DenseBase< Derived >::ColwiseReturnType colwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
rowwise(), class VectorwiseOp, Reductions, visitors and broadcasting
Constant() [1/3]
const DenseBase< Derived >::ConstantReturnType Constant (Index nbRows, Index nbCols, const Scalar & value) inline static
Returns
an expression of a constant matrix of value value
The parameters nbRows and nbCols are the number of rows and of columns of the returned matrix. Must be compatible with this DenseBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass nbRows and nbCols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
Constant() [2/3]
const DenseBase< Derived >::ConstantReturnType Constant (Index size, const Scalar & value) inline static
Returns
an expression of a constant matrix of value value
The parameter size is the size of the returned vector. Must be compatible with this DenseBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
Constant() [3/3]
const DenseBase< Derived >::ConstantReturnType Constant (const Scalar & value) inline static
Returns
an expression of a constant matrix of value value
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
count()
DenseBase< Derived >::Index count () const inline
Returns
the number of coefficients which evaluate to true
See also
all(), any()
eval()
EvalReturnType eval () const inline
Returns
the matrix or vector obtained by evaluating this expression.
Notice that in the case of a plain matrix or vector (not an expression) this function just returns a const reference, in order to avoid a useless copy.
fill()
void fill (const Scalar & val) inline
Alias for setConstant(): sets all coefficients in this expression to val.
See also
setConstant(), Constant(), class CwiseNullaryOp
Referenced by PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::determinant(), and PermutationWrapper< _IndicesType >::indices().
flagged()
const Flagged< Derived, Added, Removed > flagged () const inline
Returns
an expression of *this with added and removed flags
This is mostly for internal use.
See also
class Flagged
format()
const WithFormat< Derived > format (const IOFormat & fmt) const inline
Returns
a WithFormat proxy object allowing to print a matrix the with given format fmt.
See class IOFormat for some examples.
See also
class IOFormat, class WithFormat
hasNaN()
bool hasNaN () const inline
Returns
true is *this contains at least one Not A Number (NaN).
See also
allFinite()
head() [1/4]
SegmentReturnType head (Index n) inline
Returns
a dynamic-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head(2) << endl;
v.head(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Referenced by JacobiSVD< _MatrixType, QRPreconditioner >::compute().
head() [2/4]
ConstSegmentReturnType head (Index n) const inline
This is the const version of head(Index).
head() [3/4]
FixedSegmentReturnType<N>::Type head (Index n = N) inline
Returns
a fixed-size expression of the first coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.head(2):" << endl << v.head<2>() << endl;
v.head<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.head(2):
 7 -2
Now the vector v is:
0 0 6 6
See also
class Block
head() [4/4]
ConstFixedSegmentReturnType<N>::Type head (Index n = N) const inline
This is the const version of head<int>().
innerSize()
Index innerSize () const inline
Returns
the inner size.
Note
For a vector, this is just the size. For a matrix (non-vector), this is the minor dimension with respect to the storage order, i.e., the number of rows for a column-major matrix, and the number of columns for a row-major matrix.
isApprox()
bool isApprox (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. Two vectors and are considered to be approximately equal within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm (aka Frobenius norm L2 norm).
Because of the multiplicativeness of this comparison, one can't use this function to check whether *this is approximately equal to the zero matrix or vector. Indeed, isApprox(zero) returns false unless *this itself is exactly the zero matrix or vector. If you want to test whether *this is zero, use internal::isMuchSmallerThan(const RealScalar&, RealScalar) instead.
See also
internal::isMuchSmallerThan(const RealScalar&, RealScalar) const
Referenced by Transform< _Scalar, _Dim, _Mode, _Options >::isApprox().
isApproxToConstant()
bool isApproxToConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if all coefficients in this matrix are approximately equal to val, to within precision prec
References DenseBase< Derived >::isConstant().
Referenced by DenseBase< Derived >::LinSpaced().
isConstant()
bool isConstant (const Scalar & val, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
This is just an alias for isApproxToConstant().
Returns
true if all coefficients in this matrix are approximately equal to value, to within precision prec
Referenced by DenseBase< Derived >::isApproxToConstant().
isMuchSmallerThan() [1/2]
bool isMuchSmallerThan (const typename NumTraits< Scalar >::Real & other, const RealScalar & prec) const
Returns
true if the norm of *this is much smaller than other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm. For this reason, the value of the reference scalar other should come from the Hilbert-Schmidt norm of a reference matrix of same dimensions.
See also
isApprox(), isMuchSmallerThan(const DenseBase<OtherDerived>&, RealScalar) const
isMuchSmallerThan() [2/2]
bool isMuchSmallerThan (const DenseBase< OtherDerived > & other, const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if the norm of *this is much smaller than the norm of other, within the precision determined by prec.
Note
The fuzzy compares are done multiplicatively. A vector is considered to be much smaller than a vector within precision if
For matrices, the comparison is done using the Hilbert-Schmidt norm.
See also
isApprox(), isMuchSmallerThan(const RealScalar&, RealScalar) const
isOnes()
bool isOnes (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the matrix where all coefficients are equal to 1, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Ones();
m(0,2) += 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isOnes() returns: " << m.isOnes() << endl;
cout << "m.isOnes(1e-3) returns: " << m.isOnes(1e-3) << endl;
Output:
Here's the matrix m:
1 1 1
1 1 1
1 1 1
m.isOnes() returns: 0
m.isOnes(1e-3) returns: 1
See also
class CwiseNullaryOp, Ones()
Referenced by DenseBase< Derived >::Ones().
isZero()
bool isZero (const RealScalar & prec = NumTraits<Scalar>::dummy_precision()) const
Returns
true if *this is approximately equal to the zero matrix, within the precision given by prec.
Example:
Matrix3d m = Matrix3d::Zero();
m(0,2) = 1e-4;
cout << "Here's the matrix m:" << endl << m << endl;
cout << "m.isZero() returns: " << m.isZero() << endl;
cout << "m.isZero(1e-3) returns: " << m.isZero(1e-3) << endl;
Output:
Here's the matrix m:
     0      0 0.0001
     0      0      0
     0      0      0
m.isZero() returns: 0
m.isZero(1e-3) returns: 1
See also
class CwiseNullaryOp, Zero()
leftCols() [1/4]
ColsBlockXpr leftCols (Index n) inline
Returns
a block consisting of the left columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols(2):" << endl;
cout << a.leftCols(2) << endl;
a.leftCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols(2):
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See also
class Block, block(Index,Index,Index,Index)
Referenced by JacobiSVD< _MatrixType, QRPreconditioner >::compute().
leftCols() [2/4]
ConstColsBlockXpr leftCols (Index n) const inline
This is the const version of leftCols(Index).
leftCols() [3/4]
NColsBlockXpr<N>::Type leftCols (Index n = N) inline
Returns
a block consisting of the left columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.leftCols<2>():" << endl;
cout << a.leftCols<2>() << endl;
a.leftCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.leftCols<2>():
 7  9
-2 -6
 6 -3
 6  6
Now the array a is:
 0  0 -5 -3
 0  0  1  0
 0  0  0  9
 0  0  3  9
See also
class Block, block(Index,Index,Index,Index)
leftCols() [4/4]
ConstNColsBlockXpr<N>::Type leftCols (Index n = N) const inline
This is the const version of leftCols<int>().
LinSpaced() [1/4]
const DenseBase< Derived >::SequentialLinSpacedReturnType LinSpaced (Sequential_t , Index size, const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(Sequential,4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(Sequential,5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
LinSpaced() [2/4]
const DenseBase< Derived >::RandomAccessLinSpacedReturnType LinSpaced (Index size, const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp
References DenseBase< Derived >::NullaryExpr().
LinSpaced() [3/4]
const DenseBase< Derived >::SequentialLinSpacedReturnType LinSpaced (Sequential_t , const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. This particular version of LinSpaced() uses sequential access, i.e. vector access is assumed to be a(0), a(1), ..., a(size). This assumption allows for better vectorization and yields faster code than the random access version.
When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(Sequential,4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(Sequential,5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Index,Scalar,Scalar), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
References DenseBase< Derived >::NullaryExpr().
LinSpaced() [4/4]
const DenseBase< Derived >::RandomAccessLinSpacedReturnType LinSpaced (const Scalar & low, const Scalar & high) inline static
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
cout << VectorXi::LinSpaced(4,7,10).transpose() << endl;
cout << VectorXd::LinSpaced(5,0.0,1.0).transpose() << endl;
Output:
 7  8  9 10
   0 0.25  0.5 0.75    1
See also
setLinSpaced(Index,const Scalar&,const Scalar&), LinSpaced(Sequential_t,Index,const Scalar&,const Scalar&,Index), CwiseNullaryOp Special version for fixed size types which does not require the size parameter.
References DenseBase< Derived >::isApproxToConstant(), and DenseBase< Derived >::NullaryExpr().
maxCoeff() [1/3]
internal::traits< Derived >::Scalar maxCoeff () const inline
Returns
the maximum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
maxCoeff() [2/3]
internal::traits< Derived >::Scalar maxCoeff (IndexType * rowPtr, IndexType * colPtr) const
Returns
the maximum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
maxCoeff() [3/3]
internal::traits< Derived >::Scalar maxCoeff (IndexType * index) const
Returns
the maximum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::maxCoeff()
mean()
internal::traits< Derived >::Scalar mean () const inline
Returns
the mean of all coefficients of *this
See also
trace(), prod(), sum()
middleCols() [1/4]
ColsBlockXpr middleCols (Index startCol, Index numCols) inline
Returns
a block consisting of a range of columns of *this.
Parameters
startCol the index of the first column in the block
numCols the number of columns in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleCols(1,3) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See also
class Block, block(Index,Index,Index,Index)
middleCols() [2/4]
ConstColsBlockXpr middleCols (Index startCol, Index numCols) const inline
This is the const version of middleCols(Index,Index).
middleCols() [3/4]
NColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) inline
Returns
a block consisting of a range of columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
startCol the index of the first column in the block
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(:,1..3) =\n" << A.middleCols<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(:,1..3) =
-6  0  9
-3  3  3
 6 -3  5
-5  0 -8
 1  9  2
See also
class Block, block(Index,Index,Index,Index)
middleCols() [4/4]
ConstNColsBlockXpr<N>::Type middleCols (Index startCol, Index n = N) const inline
This is the const version of middleCols<int>().
middleRows() [1/4]
RowsBlockXpr middleRows (Index startRow, Index n) inline
Returns
a block consisting of a range of rows of *this.
Parameters
startRow the index of the first row in the block
n the number of rows in the block
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(2..3,:) =\n" << A.middleRows(2,2) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(2..3,:) =
 6  6 -3  5 -8
 6 -5  0 -8  6
See also
class Block, block(Index,Index,Index,Index)
middleRows() [2/4]
ConstRowsBlockXpr middleRows (Index startRow, Index n) const inline
This is the const version of middleRows(Index,Index).
middleRows() [3/4]
NRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) inline
Returns
a block consisting of a range of rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
startRow the index of the first row in the block
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
#include <Eigen/Core>
#include <iostream>
using namespace Eigen;
using namespace std;
int main(void)
{
    int const N = 5;
    MatrixXi A(N,N);
    A.setRandom();
    cout << "A =\n" << A << '\n' << endl;
    cout << "A(1..3,:) =\n" << A.middleRows<3>(1) << endl;
    return 0;
}
Output:
A =
  7  -6   0   9 -10
 -2  -3   3   3  -5
  6   6  -3   5  -8
  6  -5   0  -8   6
  9   1   9   2  -7
A(1..3,:) =
-2 -3  3  3 -5
 6  6 -3  5 -8
 6 -5  0 -8  6
See also
class Block, block(Index,Index,Index,Index)
middleRows() [4/4]
ConstNRowsBlockXpr<N>::Type middleRows (Index startRow, Index n = N) const inline
This is the const version of middleRows<int>().
minCoeff() [1/3]
internal::traits< Derived >::Scalar minCoeff () const inline
Returns
the minimum of all coefficients of *this.
Warning
the result is undefined if *this contains NaN.
minCoeff() [2/3]
internal::traits< Derived >::Scalar minCoeff (IndexType * rowId, IndexType * colId) const
Returns
the minimum of all coefficients of *this and puts in *row and *col its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(Index*), DenseBase::maxCoeff(Index*,Index*), DenseBase::visitor(), DenseBase::minCoeff()
minCoeff() [3/3]
internal::traits< Derived >::Scalar minCoeff (IndexType * index) const
Returns
the minimum of all coefficients of *this and puts in *index its location.
Warning
the result is undefined if *this contains NaN.
See also
DenseBase::minCoeff(IndexType*,IndexType*), DenseBase::maxCoeff(IndexType*,IndexType*), DenseBase::visitor(), DenseBase::minCoeff()
nestByValue()
const NestByValue< Derived > nestByValue () const inline
Returns
an expression of the temporary version of *this.
nonZeros()
Index nonZeros () const inline
Returns
the number of nonzero coefficients which is in practice the number of stored coefficients.
NullaryExpr() [1/3]
const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (Index rows, Index cols, const CustomNullaryOp & func) inline static
Returns
an expression of a matrix defined by a custom functor func
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
Referenced by DenseBase< Derived >::Constant(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::Identity(), and DenseBase< Derived >::LinSpaced().
NullaryExpr() [2/3]
const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (Index size, const CustomNullaryOp & func) inline static
Returns
an expression of a matrix defined by a custom functor func
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
NullaryExpr() [3/3]
const CwiseNullaryOp< CustomNullaryOp, Derived > NullaryExpr (const CustomNullaryOp & func) inline static
Returns
an expression of a matrix defined by a custom functor func
This variant is only for fixed-size DenseBase types. For dynamic-size types, you need to use the variants taking size arguments.
The template parameter CustomNullaryOp is the type of the functor.
See also
class CwiseNullaryOp
Ones() [1/3]
const DenseBase< Derived >::ConstantReturnType Ones (Index nbRows, Index nbCols) inline static
Returns
an expression of a matrix where all coefficients equal one.
The parameters nbRows and nbCols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Ones() should be used instead.
Example:
cout << MatrixXi::Ones(2,3) << endl;
Output:
1 1 1
1 1 1
See also
Ones(), Ones(Index), isOnes(), class Ones
Ones() [2/3]
const DenseBase< Derived >::ConstantReturnType Ones (Index newSize) inline static
Returns
an expression of a vector where all coefficients equal one.
The parameter newSize is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Ones() should be used instead.
Example:
cout << 6 * RowVectorXi::Ones(4) << endl;
cout << VectorXf::Ones(2) << endl;
Output:
6 6 6 6
1
1
See also
Ones(), Ones(Index,Index), isOnes(), class Ones
Ones() [3/3]
const DenseBase< Derived >::ConstantReturnType Ones () inline static
Returns
an expression of a fixed-size matrix or vector where all coefficients equal one.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Ones() << endl;
cout << 6 * RowVector4i::Ones() << endl;
Output:
1 1
1 1
6 6 6 6
See also
Ones(Index), Ones(Index,Index), isOnes(), class Ones
References DenseBase< Derived >::isOnes().
operator<<() [1/2]
CommaInitializer< Derived > operator<< (const Scalar & s) inline
Convenient operator to set the coefficients of a matrix.
The coefficients must be provided in a row major order and exactly match the size of the matrix. Otherwise an assertion is raised.
Example:
Matrix3i m1;
m1 << 1, 2, 3,
      4, 5, 6,
      7, 8, 9;
cout << m1 << endl << endl;
Matrix3i m2 = Matrix3i::Identity();
m2.block(0,0, 2,2) << 10, 11, 12, 13;
cout << m2 << endl << endl;
Vector2i v1;
v1 << 14, 15;
m2 << v1.transpose(), 16,
      v1, m1.block(1,1,2,2);
cout << m2 << endl;
Output:
1 2 3
4 5 6
7 8 9
10 11  0
12 13  0
 0  0  1
14 15 16
14  5  6
15  8  9
Note
According the c++ standard, the argument expressions of this comma initializer are evaluated in arbitrary order.
See also
CommaInitializer::finished(), class CommaInitializer
operator<<() [2/2]
CommaInitializer< Derived > operator<< (const DenseBase< OtherDerived > & other) inline
See also
operator<<(const Scalar&)
operator=() [1/3]
Derived & operator= (const DenseBase< OtherDerived > & other) inline
Copies other into *this.
Returns
a reference to *this.
operator=() [2/3]
Derived & operator= (const DenseBase< Derived > & other) inline
Special case of the template operator=, in order to prevent the compiler from generating a default operator= (issue hit with g++ 4.1)
operator=() [3/3]
Derived & operator= (const EigenBase< OtherDerived > & other)
Copies the generic expression other into *this.
The expression must provide a (templated) evalTo(Derived& dst) const function which does the actual job. In practice, this allows any user to write its own special matrix without having to modify MatrixBase
Returns
a reference to *this.
References EigenBase< Derived >::derived().
outerSize()
Index outerSize () const inline
Returns
the outer size.
Note
For a vector, this returns just 1. For a matrix (non-vector), this is the major dimension with respect to the storage order, i.e., the number of columns for a column-major matrix, and the number of rows for a row-major matrix.
prod()
internal::traits< Derived >::Scalar prod () const inline
Returns
the product of all coefficients of *this
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the product of all the coefficients:" << endl << m.prod() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the product of all the coefficients:
0.0019
See also
sum(), mean(), trace()
Referenced by SimplicialCholesky< _MatrixType, _UpLo, _Ordering >::factorize().
Random() [1/3]
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random (Index rows, Index cols) inline static
Returns
a random matrix expression
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Random() should be used instead.
Example:
cout << MatrixXi::Random(2,3) << endl;
Output:
 7  6  9
-2  6 -6
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
MatrixBase::setRandom(), MatrixBase::Random(Index), MatrixBase::Random()
Random() [2/3]
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random (Index size) inline static
Returns
a random vector expression
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Random() should be used instead.
Example:
cout << VectorXi::Random(2) << endl;
Output:
 7
-2
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary vector whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random()
Random() [3/3]
const CwiseNullaryOp< internal::scalar_random_op< typename internal::traits< Derived >::Scalar >, Derived > Random () inline static
Returns
a fixed-size random matrix or vector expression
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << 100 * Matrix2i::Random() << endl;
Output:
 700  600
-200  600
This expression has the "evaluate before nesting" flag so that it will be evaluated into a temporary matrix whenever it is nested in a larger expression. This prevents unexpected behavior with expressions involving random matrices.
See also
MatrixBase::setRandom(), MatrixBase::Random(Index,Index), MatrixBase::Random(Index)
redux()
internal::result_of<Func(typename internal::traits<Derived>::Scalar)>::type redux (const Func & func) const inline
Returns
the result of a full redux operation on the whole matrix or vector using func
The template parameter BinaryOp is the type of the functor func which must be an associative operator. Both current STL and TR1 functor styles are handled.
See also
DenseBase::sum(), DenseBase::minCoeff(), DenseBase::maxCoeff(), MatrixBase::colwise(), MatrixBase::rowwise()
replicate() [1/2]
const Replicate< Derived, RowFactor, ColFactor > replicate () const inline
Returns
an expression of the replication of *this
Example:
MatrixXi m = MatrixXi::Random(2,3);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "m.replicate<3,2>() = ..." << endl;
cout << m.replicate<3,2>() << endl;
Output:
Here is the matrix m:
 7  6  9
-2  6 -6
m.replicate<3,2>() = ...
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
 7  6  9  7  6  9
-2  6 -6 -2  6 -6
See also
VectorwiseOp::replicate(), DenseBase::replicate(Index,Index), class Replicate
replicate() [2/2]
const DenseBase< Derived >::ReplicateReturnType replicate (Index rowFactor, Index colFactor) const inline
Returns
an expression of the replication of *this
Example:
Vector3i v = Vector3i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "v.replicate(2,5) = ..." << endl;
cout << v.replicate(2,5) << endl;
Output:
Here is the vector v:
 7
-2
 6
v.replicate(2,5) = ...
 7  7  7  7  7
-2 -2 -2 -2 -2
 6  6  6  6  6
 7  7  7  7  7
-2 -2 -2 -2 -2
 6  6  6  6  6
See also
VectorwiseOp::replicate(), DenseBase::replicate<int,int>(), class Replicate
resize() [1/2]
void resize (Index newSize) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
Referenced by SparseQR< _MatrixType, _OrderingType >::lastErrorMessage().
resize() [2/2]
void resize (Index nbRows, Index nbCols) inline
Only plain matrices/arrays, not expressions, may be resized; therefore the only useful resize methods are Matrix::resize() and Array::resize(). The present method only asserts that the new size equals the old size, and does nothing else.
reverse() [1/2]
DenseBase< Derived >::ReverseReturnType reverse () inline
Returns
an expression of the reverse of *this.
Example:
MatrixXi m = MatrixXi::Random(3,4);
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the reverse of m:" << endl << m.reverse() << endl;
cout << "Here is the coefficient (1,0) in the reverse of m:" << endl
     << m.reverse()(1,0) << endl;
cout << "Let us overwrite this coefficient with the value 4." << endl;
m.reverse()(1,0) = 4;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  6 -3  1
-2  9  6  0
 6 -6 -5  3
Here is the reverse of m:
 3 -5 -6  6
 0  6  9 -2
 1 -3  6  7
Here is the coefficient (1,0) in the reverse of m:
0
Let us overwrite this coefficient with the value 4.
Now the matrix m is:
 7  6 -3  1
-2  9  6  4
 6 -6 -5  3
reverse() [2/2]
const DenseBase< Derived >::ConstReverseReturnType reverse () const inline
This is the const version of reverse().
reverseInPlace()
void reverseInPlace () inline
This is the "in place" version of reverse: it reverses *this.
In most cases it is probably better to simply use the reversed expression of a matrix. However, when reversing the matrix data itself is really needed, then this "in-place" version is probably the right choice because it provides the following additional features:
less error prone: doing the same operation with .reverse() requires special care:
m = m.reverse().eval();
this API allows to avoid creating a temporary (the current implementation creates a temporary, but that could be avoided using swap)
it allows future optimizations (cache friendliness, etc.)
See also
reverse()
rightCols() [1/4]
ColsBlockXpr rightCols (Index n) inline
Returns
a block consisting of the right columns of *this.
Parameters
n the number of columns in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols(2):" << endl;
cout << a.rightCols(2) << endl;
a.rightCols(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols(2):
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See also
class Block, block(Index,Index,Index,Index)
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set().
rightCols() [2/4]
ConstColsBlockXpr rightCols (Index n) const inline
This is the const version of rightCols(Index).
rightCols() [3/4]
NColsBlockXpr<N>::Type rightCols (Index n = N) inline
Returns
a block consisting of the right columns of *this.
Template Parameters
N the number of columns in the block as specified at compile-time
Parameters
n the number of columns in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.rightCols<2>():" << endl;
cout << a.rightCols<2>() << endl;
a.rightCols<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.rightCols<2>():
-5 -3
 1  0
 0  9
 3  9
Now the array a is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  0
 6  6  0  0
See also
class Block, block(Index,Index,Index,Index)
rightCols() [4/4]
ConstNColsBlockXpr<N>::Type rightCols (Index n = N) const inline
This is the const version of rightCols<int>().
row() [1/2]
RowXpr row (Index i) inline
Returns
an expression of the i-th row of *this. Note that the numbering starts at 0.
Example:
Matrix3d m = Matrix3d::Identity();
m.row(1) = Vector3d(4,5,6);
cout << m << endl;
Output:
1 0 0
4 5 6
0 0 1
See also
col(), class Block
Referenced by MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::array(), VectorwiseOp< ExpressionType, Direction >::cross(), Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Translation< _Scalar, _Dim >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::pretranslate(), and SPQR< _MatrixType >::solve().
row() [2/2]
ConstRowXpr row (Index i) const inline
This is the const version of row().
rowwise() [1/2]
const DenseBase< Derived >::ConstRowwiseReturnType rowwise () const inline
Returns
a VectorwiseOp wrapper of *this providing additional partial reduction operations
Example:
Matrix3d m = Matrix3d::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the sum of each row:" << endl << m.rowwise().sum() << endl;
cout << "Here is the maximum absolute value of each row:"
     << endl << m.cwiseAbs().rowwise().maxCoeff() << endl;
Output:
Here is the matrix m:
  0.68  0.597  -0.33
-0.211  0.823  0.536
 0.566 -0.605 -0.444
Here is the sum of each row:
 0.948
  1.15
-0.483
Here is the maximum absolute value of each row:
 0.68
0.823
0.605
See also
colwise(), class VectorwiseOp, Reductions, visitors and broadcasting
Referenced by Eigen::umeyama().
rowwise() [2/2]
DenseBase< Derived >::RowwiseReturnType rowwise () inline
Returns
a writable VectorwiseOp wrapper of *this providing additional partial reduction operations
See also
colwise(), class VectorwiseOp, Reductions, visitors and broadcasting
segment() [1/4]
SegmentReturnType segment (Index start, Index n) inline
Returns
a dynamic-size expression of a segment (i.e. a vector block) in *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
start the first coefficient in the segment
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment(1, 2):" << endl << v.segment(1, 2) << endl;
v.segment(1, 2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment(1, 2):
-2  6
Now the vector v is:
7 0 0 6
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, segment(Index)
segment() [2/4]
ConstSegmentReturnType segment (Index start, Index n) const inline
This is the const version of segment(Index,Index).
segment() [3/4]
FixedSegmentReturnType<N>::Type segment (Index start, Index n = N) inline
Returns
a fixed-size expression of a segment (i.e. a vector block) in *this
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
start the index of the first element in the segment
n the number of coefficients in the segment as specified at compile-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.segment<2>(1):" << endl << v.segment<2>(1) << endl;
v.segment<2>(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.segment<2>(1):
-2  6
Now the vector v is:
 7 -2  0  0
See also
class Block
segment() [4/4]
ConstFixedSegmentReturnType<N>::Type segment (Index start, Index n = N) const inline
This is the const version of segment<int>(Index).
select() [1/3]
const Select< Derived, ThenDerived, ElseDerived > select (const DenseBase< ThenDerived > & thenMatrix, const DenseBase< ElseDerived > & elseMatrix) const inline
Returns
a matrix where each coefficient (i,j) is equal to thenMatrix(i,j) if *this(i,j), and elseMatrix(i,j) otherwise.
Example:
MatrixXi m(3, 3);
m << 1, 2, 3,
     4, 5, 6,
     7, 8, 9;
m = (m.array() >= 5).select(-m, m);
cout << m << endl;
Output:
 1  2  3
 4 -5 -6
-7 -8 -9
See also
class Select
select() [2/3]
const Select< Derived, ThenDerived, typename ThenDerived::ConstantReturnType > select (const DenseBase< ThenDerived > & thenMatrix, const typename ThenDerived::Scalar & elseScalar) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the else expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
select() [3/3]
const Select< Derived, typename ElseDerived::ConstantReturnType, ElseDerived > select (const typename ElseDerived::Scalar & thenScalar, const DenseBase< ElseDerived > & elseMatrix) const inline
Version of DenseBase::select(const DenseBase&, const DenseBase&) with the then expression being a scalar value.
See also
DenseBase::select(const DenseBase<ThenDerived>&, const DenseBase<ElseDerived>&) const, class Select
setConstant()
Derived & setConstant (const Scalar & val) inline
Sets all coefficients in this expression to value.
See also
fill(), setConstant(Index,const Scalar&), setConstant(Index,Index,const Scalar&), setZero(), setOnes(), Constant(), class CwiseNullaryOp, setZero(), setOnes()
setLinSpaced() [1/2]
Derived & setLinSpaced (Index newSize, const Scalar & low, const Scalar & high) inline
Sets a linearly space vector.
The function generates 'size' equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Example:
VectorXf v;
v.setLinSpaced(5,0.5f,1.5f);
cout << v << endl;
Output:
 0.5
0.75
   1
1.25
 1.5
See also
CwiseNullaryOp
setLinSpaced() [2/2]
Derived & setLinSpaced (const Scalar & low, const Scalar & high) inline
Sets a linearly space vector.
The function fill *this with equally spaced values in the closed interval [low,high]. When size is set to 1, a vector of length 1 containing 'high' is returned.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
See also
setLinSpaced(Index, const Scalar&, const Scalar&), CwiseNullaryOp
setOnes()
Derived & setOnes () inline
Sets all coefficients in this expression to one.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setOnes();
cout << m << endl;
Output:
 7  9 -5 -3
 1  1  1  1
 6 -3  0  9
 6  6  3  9
See also
class CwiseNullaryOp, Ones()
setRandom()
Derived & setRandom () inline
Sets all coefficients in this expression to random values.
Example:
Matrix4i m = Matrix4i::Zero();
m.col(1).setRandom();
cout << m << endl;
Output:
 0  7  0  0
 0 -2  0  0
 0  6  0  0
 0  6  0  0
See also
class CwiseNullaryOp, setRandom(Index), setRandom(Index,Index)
setZero()
Derived & setZero () inline
Sets all coefficients in this expression to zero.
Example:
Matrix4i m = Matrix4i::Random();
m.row(1).setZero();
cout << m << endl;
Output:
 7  9 -5 -3
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See also
class CwiseNullaryOp, Zero()
Referenced by PermutationWrapper< _IndicesType >::indices(), and PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::size().
sum()
internal::traits< Derived >::Scalar sum () const inline
Returns
the sum of all coefficients of *this
See also
trace(), prod(), mean()
swap() [1/2]
void swap (const DenseBase< OtherDerived > & other, int = OtherDerived::ThisConstantIsPrivateInPlainObjectBase) inline
swaps *this with the expression other.
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set(), and Matrix< ComplexScalar, RowsAtCompileTime, ColsAtCompileTime, Options, MaxRowsAtCompileTime, MaxColsAtCompileTime >::Matrix().
swap() [2/2]
void swap (PlainObjectBase< OtherDerived > & other) inline
swaps *this with the matrix or array other.
tail() [1/4]
SegmentReturnType tail (Index n) inline
Returns
a dynamic-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Parameters
n the number of coefficients in the segment
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail(2) << endl;
v.tail(2).setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
Note
Even though the returned expression has dynamic size, in the case when it is applied to a fixed-size vector, it inherits a fixed maximal size, which means that evaluating it does not cause a dynamic memory allocation.
See also
class Block, block(Index,Index)
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::_set(), and LDLT< _MatrixType, _UpLo >::info().
tail() [2/4]
ConstSegmentReturnType tail (Index n) const inline
This is the const version of tail(Index).
tail() [3/4]
FixedSegmentReturnType<N>::Type tail (Index n = N) inline
Returns
a fixed-size expression of the last coefficients of *this.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
Template Parameters
N the number of coefficients in the segment as specified at compile-time
Parameters
n the number of coefficients in the segment as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
RowVector4i v = RowVector4i::Random();
cout << "Here is the vector v:" << endl << v << endl;
cout << "Here is v.tail(2):" << endl << v.tail<2>() << endl;
v.tail<2>().setZero();
cout << "Now the vector v is:" << endl << v << endl;
Output:
Here is the vector v:
 7 -2  6  6
Here is v.tail(2):
6 6
Now the vector v is:
 7 -2  0  0
See also
class Block
tail() [4/4]
ConstFixedSegmentReturnType<N>::Type tail (Index n = N) const inline
This is the const version of tail<int>.
topLeftCorner() [1/6]
Block<Derived> topLeftCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-left corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner(2, 2):" << endl;
cout << m.topLeftCorner(2, 2) << endl;
m.topLeftCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner(2, 2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See also
class Block, block(Index,Index,Index,Index)
topLeftCorner() [2/6]
const Block<const Derived> topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner(Index, Index).
topLeftCorner() [3/6]
Block<Derived, CRows, CCols> topLeftCorner () inline
Returns
an expression of a fixed-size top-left corner of *this.
The template parameters CRows and CCols are the number of rows and columns in the corner.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,2>():" << endl;
cout << m.topLeftCorner<2,2>() << endl;
m.topLeftCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,2>():
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See also
class Block, block(Index,Index,Index,Index)
topLeftCorner() [4/6]
const Block<const Derived, CRows, CCols> topLeftCorner () const inline
This is the const version of topLeftCorner<int, int>().
topLeftCorner() [5/6]
Block<Derived, CRows, CCols> topLeftCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-left corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topLeftCorner<2,Dynamic>(2,2):" << endl;
cout << m.topLeftCorner<2,Dynamic>(2,2) << endl;
m.topLeftCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topLeftCorner<2,Dynamic>(2,2):
 7  9
-2 -6
Now the matrix m is:
 0  0 -5 -3
 0  0  1  0
 6 -3  0  9
 6  6  3  9
See also
class Block
topLeftCorner() [6/6]
const Block<const Derived, CRows, CCols> topLeftCorner (Index cRows, Index cCols) const inline
This is the const version of topLeftCorner<int, int>(Index, Index).
topRightCorner() [1/6]
Block<Derived> topRightCorner (Index cRows, Index cCols) inline
Returns
a dynamic-size expression of a top-right corner of *this.
Parameters
cRows the number of rows in the corner
cCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner(2, 2):" << endl;
cout << m.topRightCorner(2, 2) << endl;
m.topRightCorner(2, 2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner(2, 2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See also
class Block, block(Index,Index,Index,Index)
topRightCorner() [2/6]
const Block<const Derived> topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner(Index, Index).
topRightCorner() [3/6]
Block<Derived, CRows, CCols> topRightCorner () inline
Returns
an expression of a fixed-size top-right corner of *this.
Template Parameters
CRows the number of rows in the corner
CCols the number of columns in the corner
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,2>():" << endl;
cout << m.topRightCorner<2,2>() << endl;
m.topRightCorner<2,2>().setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,2>():
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See also
class Block, block<int,int>(Index,Index)
topRightCorner() [4/6]
const Block<const Derived, CRows, CCols> topRightCorner () const inline
This is the const version of topRightCorner<int, int>().
topRightCorner() [5/6]
Block<Derived, CRows, CCols> topRightCorner (Index cRows, Index cCols) inline
Returns
an expression of a top-right corner of *this.
Template Parameters
CRows number of rows in corner as specified at compile-time
CCols number of columns in corner as specified at compile-time
Parameters
cRows number of rows in corner as specified at run-time
cCols number of columns in corner as specified at run-time
This function is mainly useful for corners where the number of rows is specified at compile-time and the number of columns is specified at run-time, or vice versa. The compile-time and run-time information should not contradict. In other words, cRows should equal CRows unless CRows is Dynamic, and the same for the number of columns.
Example:
Matrix4i m = Matrix4i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is m.topRightCorner<2,Dynamic>(2,2):" << endl;
cout << m.topRightCorner<2,Dynamic>(2,2) << endl;
m.topRightCorner<2,Dynamic>(2,2).setZero();
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is m.topRightCorner<2,Dynamic>(2,2):
-5 -3
 1  0
Now the matrix m is:
 7  9  0  0
-2 -6  0  0
 6 -3  0  9
 6  6  3  9
See also
class Block
topRightCorner() [6/6]
const Block<const Derived, CRows, CCols> topRightCorner (Index cRows, Index cCols) const inline
This is the const version of topRightCorner<int, int>(Index, Index).
topRows() [1/4]
RowsBlockXpr topRows (Index n) inline
Returns
a block consisting of the top rows of *this.
Parameters
n the number of rows in the block
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows(2):" << endl;
cout << a.topRows(2) << endl;
a.topRows(2).setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows(2):
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See also
class Block, block(Index,Index,Index,Index)
Referenced by SparseQR< _MatrixType, _OrderingType >::lastErrorMessage().
topRows() [2/4]
ConstRowsBlockXpr topRows (Index n) const inline
This is the const version of topRows(Index).
topRows() [3/4]
NRowsBlockXpr<N>::Type topRows (Index n = N) inline
Returns
a block consisting of the top rows of *this.
Template Parameters
N the number of rows in the block as specified at compile-time
Parameters
n the number of rows in the block as specified at run-time
The compile-time and run-time information should not contradict. In other words, n should equal N unless N is Dynamic.
Example:
Array44i a = Array44i::Random();
cout << "Here is the array a:" << endl << a << endl;
cout << "Here is a.topRows<2>():" << endl;
cout << a.topRows<2>() << endl;
a.topRows<2>().setZero();
cout << "Now the array a is:" << endl << a << endl;
Output:
Here is the array a:
 7  9 -5 -3
-2 -6  1  0
 6 -3  0  9
 6  6  3  9
Here is a.topRows<2>():
 7  9 -5 -3
-2 -6  1  0
Now the array a is:
 0  0  0  0
 0  0  0  0
 6 -3  0  9
 6  6  3  9
See also
class Block, block(Index,Index,Index,Index)
topRows() [4/4]
ConstNRowsBlockXpr<N>::Type topRows (Index n = N) const inline
This is the const version of topRows<int>().
transpose() [1/2]
Transpose< Derived > transpose () inline
Returns
an expression of the transpose of *this.
Example:
Matrix2i m = Matrix2i::Random();
cout << "Here is the matrix m:" << endl << m << endl;
cout << "Here is the transpose of m:" << endl << m.transpose() << endl;
cout << "Here is the coefficient (1,0) in the transpose of m:" << endl
     << m.transpose()(1,0) << endl;
cout << "Let us overwrite this coefficient with the value 0." << endl;
m.transpose()(1,0) = 0;
cout << "Now the matrix m is:" << endl << m << endl;
Output:
Here is the matrix m:
 7  6
-2  6
Here is the transpose of m:
 7 -2
 6  6
Here is the coefficient (1,0) in the transpose of m:
6
Let us overwrite this coefficient with the value 0.
Now the matrix m is:
 7  0
-2  6
Warning
If you want to replace a matrix by its own transpose, do NOT do this:
m = m.transpose(); // bug!!! caused by aliasing effect
Instead, use the transposeInPlace() method:
m.transposeInPlace();
which gives Eigen good opportunities for optimization, or alternatively you can also do:
m = m.transpose().eval();
See also
transposeInPlace(), adjoint()
Referenced by Hyperplane< _Scalar, _AmbientDim, _Options >::Through().
transpose() [2/2]
DenseBase< Derived >::ConstTransposeReturnType transpose () const inline
This is the const version of transpose().
Make sure you read the warning for transpose() !
See also
transposeInPlace(), adjoint()
transposeInPlace()
void transposeInPlace () inline
This is the "in place" version of transpose(): it replaces *this by its own transpose. Thus, doing
m.transposeInPlace();
has the same effect on m as doing
m = m.transpose().eval();
and is faster and also safer because in the latter line of code, forgetting the eval() results in a bug caused by aliasing.
Notice however that this method is only useful if you want to replace a matrix by its own transpose. If you just need the transpose of a matrix, use transpose().
Note
if the matrix is not square, then *this must be a resizable matrix. This excludes (non-square) fixed-size matrices, block-expressions and maps.
See also
transpose(), adjoint(), adjointInPlace()
value()
CoeffReturnType value () const inline
Returns
the unique coefficient of a 1x1 expression
Referenced by SparseLU< _MatrixType, _OrderingType >::factorize().
visit()
void visit (Visitor & visitor) const
Applies the visitor visitor to the whole coefficients of the matrix or vector.
The template parameter Visitor is the type of the visitor and provides the following interface:
struct MyVisitor {
  // called for the first coefficient
  void init(const Scalar& value, Index i, Index j);
  // called for all other coefficients
  void operator() (const Scalar& value, Index i, Index j);
};
Note
compared to one or two for loops, visitors offer automatic unrolling for small fixed size matrix.
See also
minCoeff(Index*,Index*), maxCoeff(Index*,Index*), DenseBase::redux()
Zero() [1/3]
const DenseBase< Derived >::ConstantReturnType Zero (Index nbRows, Index nbCols) inline static
Returns
an expression of a zero matrix.
The parameters rows and cols are the number of rows and of columns of the returned matrix. Must be compatible with this MatrixBase type.
This variant is meant to be used for dynamic-size matrix types. For fixed-size types, it is redundant to pass rows and cols as arguments, so Zero() should be used instead.
Example:
cout << MatrixXi::Zero(2,3) << endl;
Output:
0 0 0
0 0 0
See also
Zero(), Zero(Index)
Zero() [2/3]
const DenseBase< Derived >::ConstantReturnType Zero (Index size) inline static
Returns
an expression of a zero vector.
The parameter size is the size of the returned vector. Must be compatible with this MatrixBase type.
This is only for vectors (either row-vectors or column-vectors), i.e. matrices which are known at compile-time to have either one row or one column.
This variant is meant to be used for dynamic-size vector types. For fixed-size types, it is redundant to pass size as argument, so Zero() should be used instead.
Example:
cout << RowVectorXi::Zero(4) << endl;
cout << VectorXf::Zero(2) << endl;
Output:
0 0 0 0
0
0
See also
Zero(), Zero(Index,Index)
Zero() [3/3]
const DenseBase< Derived >::ConstantReturnType Zero () inline static
Returns
an expression of a fixed-size zero matrix or vector.
This variant is only for fixed-size MatrixBase types. For dynamic-size types, you need to use the variants taking size arguments.
Example:
cout << Matrix2d::Zero() << endl;
cout << RowVector4i::Zero() << endl;
Output:
0 0
0 0
0 0 0 0
See also
Zero(Index), Zero(Index,Index)
Friends And Related Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & s, const DenseBase< Derived > & m) related
Outputs the matrix, to the given stream.
If you wish to print the matrix with a format different than the default, use DenseBase::format().
It is also possible to change the default format by defining EIGEN_DEFAULT_IO_FORMAT before including Eigen headers. If not defined, this will automatically be defined to Eigen::IOFormat(), that is the Eigen::IOFormat with default parameters.
See also
DenseBase::format()
The documentation for this class was generated from the following files:
DenseBase.h
Assign.h
BooleanRedux.h
CommaInitializer.h
CwiseNullaryOp.h
EigenBase.h
Flagged.h
Fuzzy.h
IO.h
NestByValue.h
Random.h
Redux.h
Replicate.h
ReturnByValue.h
Reverse.h
Select.h
SelfCwiseBinaryOp.h
Transpose.h
VectorwiseOp.h
Visitor.h