Eigen: COLAMDOrdering< Index > Class Template Reference
COLAMDOrdering< Index > Class Template Reference
Sparse linear algebra » Reference » OrderingMethods_Module
Detailed Description
template<typename Index>
class Eigen::COLAMDOrdering< Index >
Functor computing the column approximate minimum degree ordering The matrix should be in column-major and compressed format (see SparseMatrix::makeCompressed()).
Public Member Functions
template<typename MatrixType >
void operator() (const MatrixType &mat, PermutationType &perm)
Member Function Documentation
operator()()
void operator() (const MatrixType & mat, PermutationType & perm) inline
Compute the permutation vector perm form the sparse matrix mat
Warning
The input sparse matrix mat must be in compressed mode (see SparseMatrix::makeCompressed()).
References Eigen::internal::colamd_recommended(), PlainObjectBase< Derived >::data(), PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType >::indices(), and PermutationBase< Derived >::resize().
The documentation for this class was generated from the following file:
Ordering.h