Eigen: TriangularView< _MatrixType, _Mode > Class Template Reference
TriangularView< _MatrixType, _Mode > Class Template Reference
Dense matrix and array manipulation » Reference » Core_Module
Detailed Description
template<typename _MatrixType, unsigned int _Mode>
class Eigen::TriangularView< _MatrixType, _Mode >
Base class for triangular part in a matrix.
Parameters
MatrixType the type of the object in which we are taking the triangular part
Mode the kind of triangular matrix expression to construct. Can be #Upper, #Lower, #UnitUpper, #UnitLower, #StrictlyUpper, or #StrictlyLower. This is in fact a bit field; it must have either #Upper or #Lower, and additionnaly it may have #UnitDiag or #ZeroDiag or neither.
This class represents a triangular part of a matrix, not necessarily square. Strictly speaking, for rectangular matrices one should speak of "trapezoid" parts. This class is the return type of MatrixBase::triangularView() and most of the time this is the only way it is used.
See also
MatrixBase::triangularView()
Inherits TriangularBase< Derived >.
Public Member Functions
const TriangularView< const typename MatrixType::AdjointReturnType, TransposeMode > adjoint () const
Scalar coeff (Index row, Index col) const
Scalar & coeffRef (Index row, Index col)
TriangularView< MatrixConjugateReturnType, Mode > conjugate ()
const TriangularView< MatrixConjugateReturnType, Mode > conjugate () const
template<typename Other >
void copyCoeff (Index row, Index col, Other &other)
Derived & derived ()
const Derived & derived () const
template<typename DenseDerived >
void evalTo (MatrixBase< DenseDerived > &other) const
template<typename DenseDerived >
void evalToLazy (MatrixBase< DenseDerived > &other) const
void fill (const Scalar &value)
template<typename OtherDerived >
TriangularProduct< Mode, true, MatrixType, false, OtherDerived, OtherDerived::ColsAtCompileTime==1 > operator* (const MatrixBase< OtherDerived > &rhs) const
TriangularView & operator*= (const typename internal::traits< MatrixType >::Scalar &other)
template<typename Other >
TriangularView & operator+= (const DenseBase< Other > &other)
template<typename Other >
TriangularView & operator-= (const DenseBase< Other > &other)
TriangularView & operator/= (const typename internal::traits< MatrixType >::Scalar &other)
template<typename OtherDerived >
TriangularView & operator= (const TriangularBase< OtherDerived > &other)
TriangularView & setConstant (const Scalar &value)
TriangularView & setOnes ()
TriangularView & setZero ()
Index size () const
template<int Side, typename Other >
const internal::triangular_solve_retval< Side, TriangularView< Derived, Mode >, Other > solve (const MatrixBase< Other > &other) const
template<int Side, typename OtherDerived >
void solveInPlace (const MatrixBase< OtherDerived > &other) const
TriangularView< Transpose< MatrixType >, TransposeMode > transpose ()
const TriangularView< Transpose< MatrixType >, TransposeMode > transpose () const
Friends
template<typename OtherDerived >
TriangularProduct< Mode, false, OtherDerived, OtherDerived::RowsAtCompileTime==1, MatrixType, false > operator* (const MatrixBase< OtherDerived > &lhs, const TriangularView &rhs)
Member Function Documentation
adjoint()
const TriangularView<const typename MatrixType::AdjointReturnType,TransposeMode> adjoint () const inline
See also
MatrixBase::adjoint() const
Referenced by LLT< _MatrixType, _UpLo >::info(), and LDLT< _MatrixType, _UpLo >::info().
coeff()
Scalar coeff (Index row, Index col) const inline
See also
MatrixBase::coeff()
Warning
the coordinates must fit into the referenced triangular part
coeffRef()
Scalar& coeffRef (Index row, Index col) inline
See also
MatrixBase::coeffRef()
Warning
the coordinates must fit into the referenced triangular part
conjugate() [1/2]
TriangularView<MatrixConjugateReturnType,Mode> conjugate () inline
See also
MatrixBase::conjugate()
conjugate() [2/2]
const TriangularView<MatrixConjugateReturnType,Mode> conjugate () const inline
See also
MatrixBase::conjugate() const
copyCoeff()
void copyCoeff (Index row, Index col, Other & other) inline inherited
See also
MatrixBase::copyCoeff(row,col)
derived() [1/2]
Derived& derived () inline inherited
Returns
a reference to the derived object
Referenced by IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::analyzePattern(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheLeft(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRightCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRows(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::compute(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::factorize(), SparseQR< _MatrixType, _OrderingType >::factorize(), PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::indices(), PermutationWrapper< _IndicesType >::indices(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::IterativeSolverBase(), SparseVector< _Scalar, _Options, _Index >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator*(), RotationBase< Derived, 3 >::operator*(), SparseSelfAdjointView< MatrixType, UpLo >::operator*(), Translation< _Scalar, _Dim >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator*=(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator=(), DenseBase< Derived >::operator=(), Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SparseMatrix< Scalar, RowMajor >::setFromTriplets(), SparseMatrix< Scalar, RowMajor >::setIdentity(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), SparseLU< _MatrixType, _OrderingType >::solve(), SparseQR< _MatrixType, _OrderingType >::solve(), UmfPackLU< _MatrixType >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), SparseVector< _Scalar, _Options, _Index >::swap(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topRightCorner(), Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
derived() [2/2]
const Derived& derived () const inline inherited
Returns
a const reference to the derived object
evalTo()
void evalTo (MatrixBase< DenseDerived > & other) const inherited
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
evalToLazy()
void evalToLazy (MatrixBase< DenseDerived > & other) const inherited
Assigns a triangular or selfadjoint matrix to a dense matrix. If the matrix is triangular, the opposite part is set to zero.
fill()
void fill (const Scalar & value) inline
See also
MatrixBase::fill()
operator*()
TriangularProduct<Mode, true, MatrixType, false, OtherDerived, OtherDerived::ColsAtCompileTime==1> operator* (const MatrixBase< OtherDerived > & rhs) const inline
Efficient triangular matrix times vector/matrix product
operator*=()
TriangularView& operator*= (const typename internal::traits< MatrixType >::Scalar & other) inline
See also
MatrixBase::operator*=()
operator+=()
TriangularView& operator+= (const DenseBase< Other > & other) inline
See also
MatrixBase::operator+=()
operator-=()
TriangularView& operator-= (const DenseBase< Other > & other) inline
See also
MatrixBase::operator-=()
operator/=()
TriangularView& operator/= (const typename internal::traits< MatrixType >::Scalar & other) inline
See also
MatrixBase::operator/=()
operator=()
TriangularView& operator= (const TriangularBase< OtherDerived > & other)
Assigns a triangular matrix to a triangular part of a dense matrix
setConstant()
TriangularView& setConstant (const Scalar & value) inline
See also
MatrixBase::setConstant()
setOnes()
TriangularView& setOnes () inline
See also
MatrixBase::setOnes()
setZero()
TriangularView& setZero () inline
See also
MatrixBase::setZero()
size()
Index size () const inline inherited
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase().
solve()
const internal::triangular_solve_retval<Side,TriangularView<Derived,Mode>,Other> solve (const MatrixBase< Other > & other) const
Returns
the product of the inverse of *this with other, *this being triangular.
This function computes the inverse-matrix matrix product inverse(*this) * other if Side==OnTheLeft (the default), or the right-inverse-multiply other * inverse(*this) if Side==OnTheRight.
The matrix *this must be triangular and invertible (i.e., all the coefficients of the diagonal must be non zero). It works as a forward (resp. backward) substitution if *this is an upper (resp. lower) triangular matrix.
Example:
#ifndef _MSC_VER
  #warning deprecated
#endif
/*
Matrix3d m = Matrix3d::Zero();
m.part<Eigen::UpperTriangular>().setOnes();
cout << "Here is the matrix m:" << endl << m << endl;
Matrix3d n = Matrix3d::Ones();
n.part<Eigen::LowerTriangular>() *= 2;
cout << "Here is the matrix n:" << endl << n << endl;
cout << "And now here is m.inverse()*n, taking advantage of the fact that"
        " m is upper-triangular:" << endl
     << m.marked<Eigen::UpperTriangular>().solveTriangular(n);
*/
Output:
This function returns an expression of the inverse-multiply and can works in-place if it is assigned to the same matrix or vector other.
For users coming from BLAS, this function (and more specifically solveInPlace()) offer all the operations supported by the *TRSV and *TRSM BLAS routines.
See also
TriangularView::solveInPlace()
solveInPlace()
void solveInPlace (const MatrixBase< OtherDerived > & _other) const
"in-place" version of TriangularView::solve() where the result is written in other
Warning
The parameter is only marked 'const' to make the C++ compiler accept a temporary expression here. This function will const_cast it, so constness isn't honored here.
See TriangularView:solve() for the details.
References Eigen::Lower, Eigen::OnTheLeft, Eigen::OnTheRight, Eigen::Upper, and Eigen::ZeroDiag.
transpose() [1/2]
TriangularView<Transpose<MatrixType>,TransposeMode> transpose () inline
See also
MatrixBase::transpose()
transpose() [2/2]
const TriangularView<Transpose<MatrixType>,TransposeMode> transpose () const inline
See also
MatrixBase::transpose() const
Friends And Related Function Documentation
operator*
TriangularProduct<Mode, false, OtherDerived, OtherDerived::RowsAtCompileTime==1, MatrixType, false> operator* (const MatrixBase< OtherDerived > & lhs, const TriangularView< _MatrixType, _Mode > & rhs) friend
Efficient vector/matrix times triangular matrix product
The documentation for this class was generated from the following files:
TriangularMatrix.h
GeneralMatrixMatrixTriangular.h
SolveTriangular.h