Eigen: JacobiSVD< _MatrixType, QRPreconditioner > Class Template Reference
JacobiSVD< _MatrixType, QRPreconditioner > Class Template Reference
Dense linear problems and decompositions » Reference » SVD_Module
Detailed Description
template<typename _MatrixType, int QRPreconditioner>
class Eigen::JacobiSVD< _MatrixType, QRPreconditioner >
Two-sided Jacobi SVD decomposition of a rectangular matrix.
Parameters
MatrixType the type of the matrix of which we are computing the SVD decomposition
QRPreconditioner this optional parameter allows to specify the type of QR decomposition that will be used internally for the R-SVD step for non-square matrices. See discussion of possible values below.
SVD decomposition consists in decomposing any n-by-p matrix A as a product
where U is a n-by-n unitary, V is a p-by-p unitary, and S is a n-by-p real positive matrix which is zero outside of its main diagonal; the diagonal entries of S are known as the singular values of A and the columns of U and V are known as the left and right singular vectors of A respectively.
Singular values are always sorted in decreasing order.
This JacobiSVD decomposition computes only the singular values by default. If you want U or V, you need to ask for them explicitly.
You can ask for only thin U or V to be computed, meaning the following. In case of a rectangular n-by-p matrix, letting m be the smaller value among n and p, there are only m singular vectors; the remaining columns of U and V do not correspond to actual singular vectors. Asking for thin U or V means asking for only their m first columns to be formed. So U is then a n-by-m matrix, and V is then a p-by-m matrix. Notice that thin U and V are all you need for (least squares) solving.
Here's an example demonstrating basic usage:
MatrixXf m = MatrixXf::Random(3,2);
cout << "Here is the matrix m:" << endl << m << endl;
JacobiSVD<MatrixXf> svd(m, ComputeThinU | ComputeThinV);
cout << "Its singular values are:" << endl << svd.singularValues() << endl;
cout << "Its left singular vectors are the columns of the thin U matrix:" << endl << svd.matrixU() << endl;
cout << "Its right singular vectors are the columns of the thin V matrix:" << endl << svd.matrixV() << endl;
Vector3f rhs(1, 0, 0);
cout << "Now consider this rhs vector:" << endl << rhs << endl;
cout << "A least-squares solution of m*x = rhs is:" << endl << svd.solve(rhs) << endl;
Output:
Here is the matrix m:
  0.68  0.597
-0.211  0.823
 0.566 -0.605
Its singular values are:
 1.19
0.899
Its left singular vectors are the columns of the thin U matrix:
  0.388   0.866
  0.712 -0.0634
 -0.586   0.496
Its right singular vectors are the columns of the thin V matrix:
-0.183  0.983
 0.983  0.183
Now consider this rhs vector:
1
0
0
A least-squares solution of m*x = rhs is:
0.888
0.496
This JacobiSVD class is a two-sided Jacobi R-SVD decomposition, ensuring optimal reliability and accuracy. The downside is that it's slower than bidiagonalizing SVD algorithms for large square matrices; however its complexity is still where n is the smaller dimension and p is the greater dimension, meaning that it is still of the same order of complexity as the faster bidiagonalizing R-SVD algorithms. In particular, like any R-SVD, it takes advantage of non-squareness in that its complexity is only linear in the greater dimension.
If the input matrix has inf or nan coefficients, the result of the computation is undefined, but the computation is guaranteed to terminate in finite (and reasonable) time.
The possible values for QRPreconditioner are:
ColPivHouseholderQRPreconditioner is the default. In practice it's very safe. It uses column-pivoting QR.
FullPivHouseholderQRPreconditioner, is the safest and slowest. It uses full-pivoting QR. Contrary to other QRs, it doesn't allow computing thin unitaries.
HouseholderQRPreconditioner is the fastest, and less safe and accurate than the pivoting variants. It uses non-pivoting QR. This is very similar in safety and accuracy to the bidiagonalization process used by bidiagonalizing SVD algorithms (since bidiagonalization is inherently non-pivoting). However the resulting SVD is still more reliable than bidiagonalizing SVDs because the Jacobi-based iterarive process is more reliable than the optimized bidiagonal SVD iterations.
NoQRPreconditioner allows not to use a QR preconditioner at all. This is useful if you know that you will only be computing JacobiSVD decompositions of square matrices. Non-square matrices require a QR preconditioner. Using this option will result in faster compilation and smaller executable code. It won't significantly speed up computation, since JacobiSVD is always checking if QR preconditioning is needed before applying it anyway.
See also
MatrixBase::jacobiSvd()
Public Member Functions
JacobiSVD & compute (const MatrixType &matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
JacobiSVD & compute (const MatrixType &matrix)
Method performing the decomposition of given matrix using current options.
bool computeU () const
bool computeV () const
JacobiSVD ()
Default Constructor.
JacobiSVD (Index rows, Index cols, unsigned int computationOptions=0)
Default Constructor with memory preallocation.
JacobiSVD (const MatrixType &matrix, unsigned int computationOptions=0)
Constructor performing the decomposition of given matrix.
const MatrixUType & matrixU () const
const MatrixVType & matrixV () const
Index nonzeroSingularValues () const
Index rank () const
JacobiSVD & setThreshold (const RealScalar &threshold)
JacobiSVD & setThreshold (Default_t)
const SingularValuesType & singularValues () const
template<typename Rhs >
const internal::solve_retval< JacobiSVD, Rhs > solve (const MatrixBase< Rhs > &b) const
RealScalar threshold () const
Constructor & Destructor Documentation
JacobiSVD() [1/3]
JacobiSVD () inline
Default Constructor.
The default constructor is useful in cases in which the user intends to perform decompositions via JacobiSVD::compute(const MatrixType&).
JacobiSVD() [2/3]
JacobiSVD (Index rows, Index cols, unsigned int computationOptions = 0) inline
Default Constructor with memory preallocation.
Like the default constructor but with preallocation of the internal data according to the specified problem size.
See also
JacobiSVD()
JacobiSVD() [3/3]
JacobiSVD (const MatrixType & matrix, unsigned int computationOptions = 0) inline
Constructor performing the decomposition of given matrix.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are #ComputeFullU, #ComputeThinU, #ComputeFullV, #ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
Member Function Documentation
compute() [1/2]
JacobiSVD< MatrixType, QRPreconditioner > & compute (const MatrixType & matrix, unsigned int computationOptions)
Method performing the decomposition of given matrix using custom options.
Parameters
matrix the matrix to decompose
computationOptions optional parameter allowing to specify if you want full or thin U or V unitaries to be computed. By default, none is computed. This is a bit-field, the possible bits are #ComputeFullU, #ComputeThinU, #ComputeFullV, #ComputeThinV.
Thin unitaries are only available if your matrix type has a Dynamic number of columns (for example MatrixXf). They also are not available with the (non-default) FullPivHouseholderQR preconditioner.
References DenseBase< Derived >::head(), DenseBase< Derived >::leftCols(), MatrixBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::noalias(), and JacobiRotation< Scalar >::transpose().
compute() [2/2]
JacobiSVD& compute (const MatrixType & matrix) inline
Method performing the decomposition of given matrix using current options.
Parameters
matrix the matrix to decompose
This method uses the current computationOptions, as already passed to the constructor or to compute(const MatrixType&, unsigned int).
computeU()
bool computeU () const inline
Returns
true if U (full or thin) is asked for in this SVD decomposition
computeV()
bool computeV () const inline
Returns
true if V (full or thin) is asked for in this SVD decomposition
matrixU()
const MatrixUType& matrixU () const inline
Returns
the U matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the U matrix is n-by-n if you asked for #ComputeFullU, and is n-by-m if you asked for #ComputeThinU.
The m first columns of U are the left singular vectors of the matrix being decomposed.
This method asserts that you asked for U to be computed.
Referenced by Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), and Eigen::umeyama().
matrixV()
const MatrixVType& matrixV () const inline
Returns
the V matrix.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the V matrix is p-by-p if you asked for #ComputeFullV, and is p-by-m if you asked for ComputeThinV.
The m first columns of V are the right singular vectors of the matrix being decomposed.
This method asserts that you asked for V to be computed.
Referenced by Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), QuaternionBase< Quaternion< _Scalar, _Options > >::setFromTwoVectors(), Hyperplane< _Scalar, _AmbientDim, _Options >::Through(), and Eigen::umeyama().
nonzeroSingularValues()
Index nonzeroSingularValues () const inline
Returns
the number of singular values that are not exactly 0
rank()
Index rank () const inline
Returns
the rank of the matrix of which *this is the SVD.
Note
This method has to determine which singular values should be considered nonzero. For that, it uses the threshold value that you can control by calling setThreshold(const RealScalar&).
setThreshold() [1/2]
JacobiSVD& setThreshold (const RealScalar & threshold) inline
Allows to prescribe a threshold to be used by certain methods, such as rank() and solve(), which need to determine when singular values are to be considered nonzero. This is not used for the SVD decomposition itself.
When it needs to get the threshold value, Eigen calls threshold(). The default is NumTraits<Scalar>::epsilon()
Parameters
threshold The new value to use as the threshold.
A singular value will be considered nonzero if its value is strictly greater than .
If you want to come back to the default behavior, call setThreshold(Default_t)
setThreshold() [2/2]
JacobiSVD& setThreshold (Default_t) inline
Allows to come back to the default behavior, letting Eigen use its default formula for determining the threshold.
You should pass the special object Eigen::Default as parameter here.
svd.setThreshold(Eigen::Default);
See the documentation of setThreshold(const RealScalar&).
singularValues()
const SingularValuesType& singularValues () const inline
Returns
the vector of singular values.
For the SVD decomposition of a n-by-p matrix, letting m be the minimum of n and p, the returned vector has size m. Singular values are always sorted in decreasing order.
Referenced by Transform< _Scalar, _Dim, _Mode, _Options >::computeRotationScaling(), Transform< _Scalar, _Dim, _Mode, _Options >::computeScalingRotation(), and Eigen::umeyama().
solve()
const internal::solve_retval<JacobiSVD, Rhs> solve (const MatrixBase< Rhs > & b) const inline
Returns
a (least squares) solution of using the current SVD decomposition of A.
Parameters
b the right-hand-side of the equation to solve.
Note
Solving requires both U and V to be computed. Thin U and V are enough, there is no need for full U or V.
SVD solving is implicitly least-squares. Thus, this method serves both purposes of exact solving and least-squares solving. In other words, the returned solution is guaranteed to minimize the Euclidean norm .
threshold()
RealScalar threshold () const inline
Returns the threshold that will be used by certain methods such as rank().
See the documentation of setThreshold(const RealScalar&).
References Eigen::ComputeFullU, Eigen::ComputeFullV, Eigen::ComputeThinU, Eigen::ComputeThinV, and Eigen::FullPivHouseholderQRPreconditioner.
The documentation for this class was generated from the following files:
ForwardDeclarations.h
JacobiSVD.h