Eigen: Geometry_Module
Geometry_Module
Geometry » Reference
Detailed Description
Modules
Global aligned box typedefs
Classes
class AlignedBox< _Scalar, _AmbientDim >
An axis aligned box.
class AngleAxis< _Scalar >
Represents a 3D rotation as a rotation angle around an arbitrary 3D axis.
class Homogeneous< MatrixType, _Direction >
Expression of one (or a set of) homogeneous vector(s)
class Hyperplane< _Scalar, _AmbientDim, _Options >
A hyperplane.
class Map< const Quaternion< _Scalar >, _Options >
Quaternion expression mapping a constant memory buffer.
class Map< Quaternion< _Scalar >, _Options >
Expression of a quaternion from a memory buffer.
class ParametrizedLine< _Scalar, _AmbientDim, _Options >
A parametrized line.
class Quaternion< _Scalar, _Options >
The quaternion class used to represent 3D orientations and rotations.
class QuaternionBase< Derived >
Base class for quaternion expressions.
class Rotation2D< _Scalar >
Represents a rotation/orientation in a 2 dimensional space.
class Scaling
Represents a generic uniform scaling transformation.
class Transform< _Scalar, _Dim, _Mode, _Options >
Represents an homogeneous transformation in a N dimensional space.
class Translation< _Scalar, _Dim >
Represents a translation transformation.
Typedefs
typedef Transform< double, 2, Affine > Affine2d
typedef Transform< float, 2, Affine > Affine2f
typedef Transform< double, 3, Affine > Affine3d
typedef Transform< float, 3, Affine > Affine3f
typedef Transform< double, 2, AffineCompact > AffineCompact2d
typedef Transform< float, 2, AffineCompact > AffineCompact2f
typedef Transform< double, 3, AffineCompact > AffineCompact3d
typedef Transform< float, 3, AffineCompact > AffineCompact3f
typedef DiagonalMatrix< double, 2 > AlignedScaling2d
typedef DiagonalMatrix< float, 2 > AlignedScaling2f
typedef DiagonalMatrix< double, 3 > AlignedScaling3d
typedef DiagonalMatrix< float, 3 > AlignedScaling3f
typedef AngleAxis< double > AngleAxisd
typedef AngleAxis< float > AngleAxisf
typedef Transform< double, 2, Isometry > Isometry2d
typedef Transform< float, 2, Isometry > Isometry2f
typedef Transform< double, 3, Isometry > Isometry3d
typedef Transform< float, 3, Isometry > Isometry3f
typedef Transform< double, 2, Projective > Projective2d
typedef Transform< float, 2, Projective > Projective2f
typedef Transform< double, 3, Projective > Projective3d
typedef Transform< float, 3, Projective > Projective3f
typedef Quaternion< double > Quaterniond
typedef Quaternion< float > Quaternionf
typedef Map< Quaternion< double >, Aligned > QuaternionMapAlignedd
typedef Map< Quaternion< float >, Aligned > QuaternionMapAlignedf
typedef Map< Quaternion< double >, 0 > QuaternionMapd
typedef Map< Quaternion< float >, 0 > QuaternionMapf
typedef Rotation2D< double > Rotation2Dd
typedef Rotation2D< float > Rotation2Df
Functions
Matrix< Scalar, 3, 1 > eulerAngles (Index a0, Index a1, Index a2) const
template<typename Derived , typename OtherDerived >
internal::umeyama_transform_matrix_type< Derived, OtherDerived >::type umeyama (const MatrixBase< Derived > &src, const MatrixBase< OtherDerived > &dst, bool with_scaling=true)
Returns the transformation between two point sets.
Typedef Documentation
Affine2d
typedef Transform<double,2,Affine> Affine2d
Affine2f
typedef Transform<float,2,Affine> Affine2f
Affine3d
typedef Transform<double,3,Affine> Affine3d
Affine3f
typedef Transform<float,3,Affine> Affine3f
AffineCompact2d
typedef Transform<double,2,AffineCompact> AffineCompact2d
AffineCompact2f
typedef Transform<float,2,AffineCompact> AffineCompact2f
AffineCompact3d
typedef Transform<double,3,AffineCompact> AffineCompact3d
AffineCompact3f
typedef Transform<float,3,AffineCompact> AffineCompact3f
AlignedScaling2d
typedef DiagonalMatrix<double,2> AlignedScaling2d
Deprecated:
AlignedScaling2f
typedef DiagonalMatrix<float, 2> AlignedScaling2f
Deprecated:
AlignedScaling3d
typedef DiagonalMatrix<double,3> AlignedScaling3d
Deprecated:
AlignedScaling3f
typedef DiagonalMatrix<float, 3> AlignedScaling3f
Deprecated:
AngleAxisd
typedef AngleAxis<double> AngleAxisd
double precision angle-axis type
AngleAxisf
typedef AngleAxis<float> AngleAxisf
single precision angle-axis type
Isometry2d
typedef Transform<double,2,Isometry> Isometry2d
Isometry2f
typedef Transform<float,2,Isometry> Isometry2f
Isometry3d
typedef Transform<double,3,Isometry> Isometry3d
Isometry3f
typedef Transform<float,3,Isometry> Isometry3f
Projective2d
typedef Transform<double,2,Projective> Projective2d
Projective2f
typedef Transform<float,2,Projective> Projective2f
Projective3d
typedef Transform<double,3,Projective> Projective3d
Projective3f
typedef Transform<float,3,Projective> Projective3f
Quaterniond
typedef Quaternion<double> Quaterniond
double precision quaternion type
Quaternionf
typedef Quaternion<float> Quaternionf
single precision quaternion type
QuaternionMapAlignedd
typedef Map<Quaternion<double>, Aligned> QuaternionMapAlignedd
Map a 16-byte aligned array of double precision scalars as a quaternion
QuaternionMapAlignedf
typedef Map<Quaternion<float>, Aligned> QuaternionMapAlignedf
Map a 16-byte aligned array of single precision scalars as a quaternion
QuaternionMapd
typedef Map<Quaternion<double>, 0> QuaternionMapd
Map an unaligned array of double precision scalars as a quaternion
QuaternionMapf
typedef Map<Quaternion<float>, 0> QuaternionMapf
Map an unaligned array of single precision scalars as a quaternion
Rotation2Dd
typedef Rotation2D<double> Rotation2Dd
double precision 2D rotation type
Rotation2Df
typedef Rotation2D<float> Rotation2Df
single precision 2D rotation type
Function Documentation
eulerAngles()
Matrix< typename MatrixBase< Derived >::Scalar, 3, 1 > eulerAngles (Index a0, Index a1, Index a2) const inline
This is defined in the Geometry module.
#include <Eigen/Geometry>
Returns
the Euler-angles of the rotation matrix *this using the convention defined by the triplet (a0,a1,a2)
Each of the three parameters a0,a1,a2 represents the respective rotation axis as an integer in {0,1,2}. For instance, in:
Vector3f ea = mat.eulerAngles(2, 0, 2);
"2" represents the z axis and "0" the x axis, etc. The returned angles are such that we have the following equality:
mat == AngleAxisf(ea[0], Vector3f::UnitZ())
     * AngleAxisf(ea[1], Vector3f::UnitX())
     * AngleAxisf(ea[2], Vector3f::UnitZ());
This corresponds to the right-multiply conventions (with right hand side frames).
The returned angles are in the ranges [0:pi]x[-pi:pi]x[-pi:pi].
See also
class AngleAxis
Referenced by MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::array().
umeyama()
internal::umeyama_transform_matrix_type<Derived, OtherDerived>::type Eigen::umeyama (const MatrixBase< Derived > & src, const MatrixBase< OtherDerived > & dst, bool with_scaling = true)
Returns the transformation between two point sets.
This is defined in the Geometry module.
#include <Eigen/Geometry>
The algorithm is based on: "Least-squares estimation of transformation parameters between two point patterns", Shinji Umeyama, PAMI 1991, DOI: 10.1109/34.88573
It estimates parameters and such that
is minimized.
The algorithm is based on the analysis of the covariance matrix of the input point sets and where is corresponding to the dimension (which is typically small). The analysis is involving the SVD having a complexity of though the actual computational effort lies in the covariance matrix computation which has an asymptotic lower bound of when the input point sets have dimension .
Currently the method is working only for floating point matrices.
Parameters
src Source points .
dst Destination points .
with_scaling Sets when false is passed.
Returns
The homogeneous transformation
minimizing the resudiual above. This transformation is always returned as an Eigen::Matrix.
References DenseBase< Derived >::colwise(), Eigen::ComputeFullU, Eigen::ComputeFullV, JacobiSVD< _MatrixType, QRPreconditioner >::matrixU(), JacobiSVD< _MatrixType, QRPreconditioner >::matrixV(), DenseBase< Derived >::rowwise(), and JacobiSVD< _MatrixType, QRPreconditioner >::singularValues().