Eigen: EigenBase< Derived > Struct Template Reference
EigenBase< Derived > Struct Template Reference
Detailed Description
template<typename Derived>
struct Eigen::EigenBase< Derived >
Common base class for all classes T such that MatrixBase has an operator=(T) and a constructor MatrixBase(T).
In other words, an EigenBase object is an object that can be copied into a MatrixBase.
Besides MatrixBase-derived classes, this also includes special matrix classes such as diagonal matrices, etc.
Notice that this class is trivial, it is only used to disambiguate overloaded functions.
See also
The class hierarchy
Public Member Functions
Index cols () const
Derived & derived ()
const Derived & derived () const
Index rows () const
Index size () const
Member Function Documentation
cols()
Index cols (void) const inline
Returns
the number of columns.
See also
rows(), ColsAtCompileTime
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), and EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size().
derived() [1/2]
Derived& derived () inline
Returns
a reference to the derived object
Referenced by IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::analyzePattern(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheLeft(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::applyOnTheRight(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRightCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::bottomRows(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::cols(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::cols(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::compute(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::eval(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::factorize(), SparseQR< _MatrixType, _OrderingType >::factorize(), PermutationMatrix< RowsAtCompileTime, MaxRowsAtCompileTime >::indices(), PermutationWrapper< _IndicesType >::indices(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::innerSize(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::IterativeSolverBase(), SparseVector< _Scalar, _Options, _Index >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::nonZeros(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::operator*(), RotationBase< Derived, 3 >::operator*(), SparseSelfAdjointView< MatrixType, UpLo >::operator*(), Translation< _Scalar, _Dim >::operator*(), PermutationBase< PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, IndexType > >::operator*(), Transform< _Scalar, _Dim, _Mode, _Options >::operator*(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator*=(), MatrixBase< DiagonalProduct< MatrixType, DiagonalType, ProductOrder > >::operator=(), DenseBase< Derived >::operator=(), Transform< _Scalar, _Dim, _Mode, _Options >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::operator=(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::resizeLike(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::rows(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::rows(), SparseMatrix< Scalar, RowMajor >::setFromTriplets(), SparseMatrix< Scalar, RowMajor >::setIdentity(), EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size(), SimplicialCholeskyBase< SimplicialLDLT< _MatrixType, _UpLo, _Ordering > >::solve(), IterativeSolverBase< ConjugateGradient< _MatrixType, _UpLo, _Preconditioner > >::solve(), SparseLU< _MatrixType, _OrderingType >::solve(), SparseQR< _MatrixType, _OrderingType >::solve(), UmfPackLU< _MatrixType >::solve(), CholmodBase< _MatrixType, _UpLo, CholmodSimplicialLLT< _MatrixType, _UpLo > >::solve(), SuperLUBase< _MatrixType, SuperILU< _MatrixType > >::solve(), SparseMatrix< Scalar, RowMajor >::SparseMatrix(), SparseVector< _Scalar, _Options, _Index >::swap(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topLeftCorner(), SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::topRightCorner(), Transform< _Scalar, _Dim, _Mode, _Options >::Transform(), and SparseMatrixBase< CwiseBinaryOp< BinaryOp, Lhs, Rhs > >::twistedBy().
derived() [2/2]
const Derived& derived () const inline
Returns
a const reference to the derived object
rows()
Index rows (void) const inline
Returns
the number of rows.
See also
cols(), RowsAtCompileTime
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase(), and EigenBase< SparseSymmetricPermutationProduct< MatrixType, UpLo > >::size().
size()
Index size () const inline
Returns
the number of coefficients, which is rows()*cols().
See also
rows(), cols(), SizeAtCompileTime.
Referenced by PlainObjectBase< Matrix< _Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols > >::PlainObjectBase().
The documentation for this struct was generated from the following file:
EigenBase.h